<?php
use src\sistema\Menubar\Menubar;
use src\sistema\Headerbar\Headerbar;
?>
<div id="db-wrapper" class="">
    <!-- navbar vertical -->
    <!-- Sidebar -->
    <?php Menubar::DibujarMenu(); ?>

    <!-- Page Content -->
    <div id="page-content">

        <!-- Page Header -->
        <?php Headerbar::DibujarHeader( ); ?>
            
        <!-- Container fluid -->
        <div class="container-fluid p-4">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-12">
                        <div class="border-bottom pb-4 mb-4 d-lg-flex justify-content-between align-items-center">
                            <div class="mb-3 mb-lg-0">
                                <h1 class="mb-0 h2 fw-bold"><?php print_r( $this->getMensaje() ); ?></h1>
                            </div>
                        </div>
                    </div>
                </div>
        </div>

    </div>
</div>