<?php
use src\sistema\Menubar\Menubar;
use src\sistema\Headerbar\Headerbar;

$usu = OperacionesCtrl::authRequ();

$l_flujositems = array();
try {
    $l_flujositems = OperacionesCtrl::flujositems_Obtener( [ 'w_usuarios_id' => $usu->getId() ] );
} catch (Exception $e) {
    throw $e;
}

$paraRevisar = [];
foreach ($l_flujositems as $kFluI ) {
    $paraRevisar[] = $kFluI['id'];
}

?>
<div id="db-wrapper" class="">
    <!-- navbar vertical -->
    <!-- Sidebar -->
    <?php $crum = Menubar::DibujarMenu(); ?>

    <!-- Page Content -->
    <div id="page-content">

        <!-- Page Header -->
        <?php Headerbar::DibujarHeader( ); ?>
            
        <!-- Container fluid -->
        <div class="container-fluid p-4">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-12">
					<div class="border-bottom pb-4 mb-4 d-lg-flex justify-content-between align-items-center">
						<div class="mb-3 mb-lg-0">
							<h1 class="mb-0 h2 fw-bold"><?php echo $crum['l2']; ?></h1>

							<nav aria-label="breadcrumb">
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="#"><?php echo $crum['l1']; ?></a></li>
									<li class="breadcrumb-item active" aria-current="page">
										<?php echo $crum['l2']; ?>
									</li>
								</ol>
							</nav>

						</div>

					</div>
				</div>
			</div>

			<div class="card" id="contCardProcs">
				<div class="card-body">
					<h4 class="mb-0">Lista de procesos</h4>
					<p class="mb-4">
						Aqu&iacute; encuentra sus procesos y el estado de los mismos
					</p>
					
					<div class="row" id="contTb">
                    	<div class="col-3">
                        	<div class="d-flex align-items-center">
                              <strong>Loading...</strong>
                              <div class="spinner-border spinner-border-sm ms-auto" role="status" aria-hidden="true"></div>
                            </div>
                    	</div>
                    </div>
					
				</div>
			</div>
			
			<div class="card" id="contProce" style="display: none;">
				<div class="card-body">
    				<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                        <ol id="olBreadcrumbFlujo" class="breadcrumb"></ol>
                    </nav>
                </div>
				<div id="cardDocs" class="card-body" style="display: none;" ></div>
				<div id="cardProcs" class="card-body"></div>
			</div>

        </div>

    </div>
</div>


<script type="application/javascript" src="./temas/js/DataTables/datatables.min.js"></script>
<script type="application/javascript">
let idMod = null;

const d_paraRevisar = <?php echo json_encode( $paraRevisar ); ?>;

const Requerimientos = function( dC ){ // dC = data constructor
	const _this = this;
	const tablaCont = dC['tableContainer'];
	let tbInter = null;
	let tableId = dC['tableId'] || "tbInt" + ut.GetUUID();
	
	let nofirmante = 0;
	let nextname = "";
	let nextid = 0;
	
	_this.dibujarTb = function(){
		const html = [];
		
		html.push('<table id="' + tableId + '" class="table table-sm table-bordered table-striped table-hover responsive" style="width: 100%;"></table>');
		
		return html.join('');
	};
	
	_this.btnCloseModInfo = function( o ){
		const _o = jQuery( o );
		const dt = _o.data();
		
		const target = jQuery( dt['target'] );
		
		const contCardProcs = jQuery('#contCardProcs');
		
		target.hide('fast');
		contCardProcs.show('fast');
		
		idMod = null;
	};
	
	_this.continuar = function( o ){
		const _o = jQuery( o );
    	const dt = _o.data();
    
    	closeAllModal();
    	
    	const opc = { 'id' : 'ajaxldr' };
        const objmdl = mngModal.dibujar( opc );
        jQuery( objmdl ).modal('show');
        
        const form_data = new FormData();
        form_data.append('ajax', '<?php echo md5( IndexCtrl::API_PaquetesHelperMoveAdmin ); ?>');
        form_data.append('data', ut.b64EncodeUnicode( JSON.stringify( dt ) ) );

		__TransportarData(
			form_data,
			function( oDt ) {
				_this.btnCloseModInfo( o );
				_this.recargarTabla();
				setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
			},
			function ( err ) {
                const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err' } );
                const alerta = jQuery(objmdlErr + ' div.alert');
                alerta.attr('class','alert alert-danger');
                
                let htmltxt = err.responseText;
                try {
					const res = JSON.parse( err.responseText );
					htmltxt = res['msj'];
				} catch (e) {
					// nada
				}
                alerta.html( htmltxt );

                jQuery( objmdlErr ).modal('show');
				setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
			}
		);
		
	};
	
    _this.firmarPdf = function( o ){
    	const _o = jQuery( o );
    	const dt = _o.data();
    
    	closeAllModal();
    	
    	const opc = { 'id' : 'ajaxldr' };
        const objmdl = mngModal.dibujar( opc );
        jQuery( objmdl ).modal('show');
        
        const form_data = new FormData();
        form_data.append('ajax', '<?php echo md5( IndexCtrl::API_FirmasproHelperAdd ); ?>');
        form_data.append('data', ut.b64EncodeUnicode( JSON.stringify( dt ) ) );
        form_data.append('u', [] );

		__TransportarData(
			form_data,
			function( o ) {
				
				setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
			},
			function ( err ) {
                const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err' } );
                const alerta = jQuery(objmdlErr + ' div.alert');
                alerta.attr('class','alert alert-danger');
                
                let htmltxt = err.responseText;
                try {
					const res = JSON.parse( err.responseText );
					htmltxt = res['msj'];
				} catch (e) {
					// nada
				}
                alerta.html( htmltxt );

                jQuery( objmdlErr ).modal('show');
				setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
			}
		);
    };
	
	_this.verPdf = function( o ){	
		const _o = jQuery( o );
		const dt = _o.data();
		
		const _urlpdf = dt['url'];
		
		const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Vista previa','btnCerrarX' : true, 'level' : 'l1', 'size' : 'modal-lg' } );
        const cuerpo = jQuery(objmdlErr + ' .modal-body');
        
        const _html = [];
        _html.push( '<div class="modal-body p-0" style="height: 50vh;">' );
        _html.push( '	<iframe src="' + _urlpdf + '#toolbar=1" style="width:100%; height:100%; border:none;"  allowfullscreen ></iframe>' );
        _html.push( '</div >' );
        
        cuerpo.html( _html.join('') );
        
        const pieHtml = [];
        pieHtml.push('<div class="modal-footer">');
        pieHtml.push('	<a href="' + _urlpdf + '" target="_blank" class="btn btn-outline-primary">');
        pieHtml.push('		Abrir en nueva pestaña');
        pieHtml.push('	</a>');
        pieHtml.push('	<button data-razon="Aprobado" data-fldcampo="FIRMA_' + nofirmante + '" data-fldtipo="proceso" data-documento="' + _urlpdf + '" data-tipousuario="<?php echo OperacionesCtrl::FIRMASPRO_TIPOUSUARIO_ADMIN ?>" type="button" class="btn btn-primary" onclick="reqs.firmarPdf( this );" >Firmar</button>');
        pieHtml.push('	<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>');
		pieHtml.push('</div>');
        cuerpo.after( pieHtml.join('') );

        jQuery( objmdlErr ).modal('show');
	};
	
	const breadcrumbFlujo = function( dt ){
		const flujoinfo = dt['firmantes'];
		const soli = dt['solicitante'];
		const olBreadcrumbFlujo = jQuery('#olBreadcrumbFlujo');
		
		const nombrefull = ( "" + jQuery.trim( soli['nombres'] + ' ' + soli['apellidos'] )).toLowerCase();
		
		const li = [];
		li.push( '<li class="breadcrumb-item text-muted" style="text-transform: capitalize;">' + nombrefull + '</li>' );
		
		let nextfir = false;
		for ( const key in flujoinfo ) {
    	    if ( Object.hasOwnProperty.call( flujoinfo, key ) ) {
    	        const _el = flujoinfo[ key ];
    	        
    	        if( nextfir == true ){
    	        	nextname = _el['nombre'];
    	        	nextid = _el['id'];
    	        }
    	        
    	        let txt = _el['nombre'];
    	        if( _el['actual'] == true ){
    	        	txt = '<a href="#"><strong>' + _el['nombre'] + '</strong></a>';
    	        	nofirmante = _el['firmante'];
    	        	nextfir = true;
    	        }
    	        
    	        li.push( '<li class="breadcrumb-item">' + txt + '</li>' );
	        }
        }
		
		olBreadcrumbFlujo.html( li.join('') );
	};
	
	const btnModInfoHtml = function( d ){
		const res = d['res'];
		const docs = res['docs'];
		const firmantes = res['firmantes'];
		const solicitante = res['solicitante'];
		
		const nombrefull = ( "" + jQuery.trim( solicitante['nombres'] + ' ' + solicitante['apellidos'] )).toLowerCase();
		
		breadcrumbFlujo( { 'firmantes' : firmantes, 'solicitante' : solicitante } );
		
		const html = [];
		///html.push('<div class="">');
		html.push('	<div class="d-flex justify-content-between">');
		html.push('		<div class="">');
		html.push('			<button id="btnVolverSolicitudes" class="btn btn-outline-danger" data-target="#contProce" onclick="reqs.btnCloseModInfo( this )" ><i class="bi bi-chevron-left"></i> Volver</button>');
		html.push('		</div>');
		html.push('		<div class="">');
		//html.push('			<button id="btnDevolver" class="btn btn-warning" data-target="#contProce" onclick="reqs.btnCloseModInfo( this )" >Devolver a <span style="text-transform: capitalize;">' + nombrefull + '</span></button>');
		html.push('		</div>');
		html.push('		<div class="">');
		html.push('			<button style="display: none;" id="btnContinuar" class="btn btn-outline-success" onclick="reqs.continuar( this );" data-target="#contProce" data-nid="' + nextid + '" data-idMod="' + idMod + '" >Continuar con ' + nextname + '</button>');
		html.push('			<button style="display: none;" id="btnFinalizar" class="btn btn-outline-success" onclick="reqs.continuar( this );" data-target="#contProce" data-idMod="' + idMod + '" data-fin="true">Finalizar solicitud</button>');
		html.push('		</div>');
		html.push('	</div>');
		html.push('	<div class="mt-3">');
		html.push('		<h4 class="mb-0">Documentos</h4>');
		html.push('		<div class="list-group">');
		
		for (const key in docs) {
    	    if (Object.hasOwnProperty.call( docs, key ) ) {
    	        const _el = docs[key];
    	        
    	        const bs = _el['bs'];
    	        const url = _el['url'];
    	        const fl = ut.pathInfo( bs );
    	        
    	        const fancy = ( "" + fl['filename'] ).replace(/sig_/ig, "").replace(/_/ig," ");
    	        
				html.push('			<button data-url="' + _el['bs'] + '" data-firmantes=" + ut.b64EncodeUnicode( JSON.stringify( firmantes ) ) + " onclick="reqs.verPdf( this );" type="button" class="list-group-item list-group-item-action">' + fancy + '</button>');
			}
		}
		html.push('		</div>');
		html.push('	</div>');
		//html.push('</div>');

    	return html.join('');
	};
	
	const formRequsHtml = function( d ){
		const html = [];
		
        for (const key in d) {
    	    if (Object.hasOwnProperty.call( d, key ) ) {
    	        const _el = d[key];
    	        
    	        let requerido = false;
    	        let requeridoEle = "";
    	        if( _el['requerido'] == 1 ){
    	        	requerido = true;
    	        	requeridoEle = "*";
    	        }
    	        
    	        const elName = _el['paquetereqtipos'] + '_' +  _el['id'];
    	        const elemCfg = { 'id' : elName, 'tipo' : _el['paquetereqtipos'], 'requerido' : requerido };
    	        
    	        html.push('<div class="mb-3 col-md-12" style="">');
    	        html.push('	<label class="form-label" for="' + elName + '">' + _el['ref'] + ' ' + requeridoEle + '</label>');
    	        html.push('	' +  home.entradasCampos( elemCfg ) );
    	        html.push('	<small class="text-muted" >' + _el['descripcion'] + '</small>');
    	        html.push('</div >');
			}
		}
		
		const formu = [];
		formu.push('<form id="frmval" class="frmvalcls">');
		formu.push( html.join('') );
		formu.push('	<div class="d-grid gap-2">');
		formu.push('		<button class="btn btn-primary" type="button" rol="button" >Enviar</button>');
		formu.push('	</div >');
		formu.push('</form >');
		
		return formu.join('');
	};
	
	_this.modInfo = function( o ){
		const _o = jQuery( o );
		const dt = _o.data();
		
		idMod = dt['id'];
		
		const target = jQuery( dt['target'] );
		
		const contProce = jQuery('#contProce');
		const card = contProce.find('#cardProcs');
		
		card.html('');
    		
    	closeAllModal();
    	
		const opc = { 'id' : 'ajaxldr' };
        const objmdl = mngModal.dibujar( opc );
        jQuery( objmdl ).modal('show');
        
        const form_data = new FormData();
        form_data.append('ajax', '<?php echo md5( IndexCtrl::API_FlujositemsRevDtGet ); ?>');
        form_data.append('data', ut.b64EncodeUnicode( JSON.stringify( dt ) ) );

		__TransportarData(
			form_data,
			function( o ) {
				const result = o['result'];
				target.hide('fast');
		
        		contProce.show("fast", function(){
        			card.html( btnModInfoHtml( { 'res': result } ) );
        			
        			if( nextname === "" ){
        				jQuery('#btnFinalizar').show('fast');
        				jQuery('#btnContinuar').hide('fast');
        			}
        			else{
        				jQuery('#btnFinalizar').hide('fast');
        				jQuery('#btnContinuar').show('fast');
        			}
        			
        		});
				setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
			},
			function ( err ) {
                const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err' } );
                const alerta = jQuery(objmdlErr + ' div.alert');
                alerta.attr('class','alert alert-danger');
                alerta.html( err.responseText );

                jQuery( objmdlErr ).modal('show');
				setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
			}
		);
		
		
	};
	
	const btnInfoHtml = function( dtInfo ){
		const html = [];
    	html.push('<button onclick="reqs.modInfo(this);" data-flujos_id="' + dtInfo.flujos_id + '" data-empleados_id="' + dtInfo.empleados_id + '" data-id="' + dtInfo.id + '" data-flujositems_id="' + dtInfo.flujositems_id + '" data-target="#contCardProcs" data-nombre="' + dtInfo.nombre + '" class="btn m-0 px-1 py-0 text-muted text-primary-hover" data-template="modTpl' + dtInfo.id + '">');
        html.push('	<i class="bi bi-eye-fill fs-5"></i>');
        html.push('	<div id="modTpl' + dtInfo.id + '" class="d-none">');
        html.push('		<h6 class="mb-0 text-white">Editar</h6>');
        html.push('	</div>');
        html.push('</button>');
        return html.join('');
	};
	
	_this.dibujarDataTable = function(){
		const tb = _this.dibujarTb();
		jQuery( tablaCont ).html( tb );
		
		tbInter = jQuery( '#' + tableId ).DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: './index.php',
                data : function(d){
                	d.ajax = '<?php echo md5( IndexCtrl::API_PaquetesGetAjax ); ?>';
                	d.columns[ 6 ]['search']['value'] = 2;
                	d.columns[ 4 ]['search']['value'] = d_paraRevisar;
                },
                type: 'POST'
            },
            columns: [
                { 'title' : 'Id', data: 'id' },
                { 'title' : 'Nombre', data: 'nombre' },
                {
                	'title' : 'Mes',
                	data: 'mesaplica',
                	render: function(data, type, row) {
                        if (!data) return '';
                
                        let fecha = new Date(data);
                        let yyyy = fecha.getFullYear();
                        let mm = fecha.getMonth() + 1;
                        
                        mm = mm < 10 ? '0' + mm : mm;
                
                        return yyyy + '-' + mm ;
                    }
                },
                { 'title' : 'Creado', data: 'fecha' },
                { 'title' : 'Proceso', data: 'flujositems_id', visible : false  },
                { 'title' : 'Usuario', data: 'empleados' },
                { 'title' : 'Estado', data: 'paquetesestados_id', visible : false },
                { 'title' : 'Plantilla', data: 'flujos_id', visible : false  },
                { data: 'empleados_id', visible : false },
                {
                    title: 'Acciones',
                    data: null,
                    orderable: false,
                    width: '1%',
                    render: function(data, type, row) {
                    	const btnInfo = btnInfoHtml( row );
                    	
                        return `
                        <div class="d-flex justify-content-start">
                            ${btnInfo}
                        </div>
                        `;
                    }
                }
            ],
            order: [[3, 'desc']],
            responsive: false,
            language: lengua_es,
            processing: true
        });
		
	};
	
    _this.recargarTabla = function () {
        if ( tbInter ) {
			tbInter.ajax.reload(null, false);
        }
    };
};

const chkArchivo = function( o ){
	chkUploadFiles( o, <?php echo Utiles::getPostMaxSizeMB() ; ?>, function( fl ){
		console.log( fl );
	});
};


let reqs = null;
const listaProcesos = function(){
	const dataConstruct = {
    	'tableContainer' : '#contTb'
    };
	reqs = new Requerimientos ( dataConstruct );
	reqs.dibujarDataTable();
};
jQuery( document ).ready(function(){
	listaProcesos();
});
</script>
