<?php
use src\sistema\Menubar\Menubar;
use src\sistema\Headerbar\Headerbar;

$cfg = OperacionesCtrl::LeerConfigCorp();

// Almacenamiento
$_CFG_ALMACENAMIENTO_TAMANO = intval( isset( $cfg[ OperacionesCtrl::CFG_ALMACENAMIENTO_TAMANO ]) ? $cfg[ OperacionesCtrl::CFG_ALMACENAMIENTO_TAMANO ]["val"] : '5' );

// Deducciones
//$_CFG_DEDUCCIONES_DATA = intval( isset( $cfg[ OperacionesCtrl::CFG_DEDUCCIONES_DATA ]) ? $cfg[ OperacionesCtrl::CFG_DEDUCCIONES_DATA ]["val"] : base64_encode( '[]' ) );

$usu = null;
if ( Seguridad::isLogin() ) {
    $usu = $_SESSION["usu"];
}

$filtroUsr = array(
    'perfil_id' => array(
        OperacionesCtrl::USUARIOS_PERFIL_ADMINISTRADOR,
        OperacionesCtrl::USUARIOS_PERFIL_FINANCIERO,
        OperacionesCtrl::USUARIOS_PERFIL_SUPERVISOR,
        OperacionesCtrl::USUARIOS_PERFIL_SUPERVISORADM,
        OperacionesCtrl::USUARIOS_PERFIL_API
        //,OperacionesCtrl::USUARIOS_PERFIL_SUPER_USUARIO
    )
);

$d_usuarios = null;
try {
    $d_usuarios = OperacionesCtrl::usuarios_Obtener( $filtroUsr );
} catch (\Throwable $th) {
    throw new \Exception( $th->getMessage() );
}

$d_tpls = array();
try {
    $d_tpls = OperacionesCtrl::editarPlantillas_Obtener( array() );
} catch (\Throwable $th) {
    throw new \Exception( $th->getMessage() );
}

?>
<style>
/* Asegura que el contenedor permita el scroll */
.table-responsive-custom {
    width: 100%;
    overflow-x: auto;
    -webkit-overflow-scrolling: touch; /* Suavidad en móviles */
    margin-bottom: 1rem;
}

/* Evita que el texto de las celdas se amontone, forzando el scroll */
table.dataTable.nowrap th, 
table.dataTable.nowrap td {
    white-space: nowrap;
}


.gu-mirror.d-flex {
    display: flex !important;
}

.gu-over {
    background-color: rgba(0, 123, 255, 0.05) !important;
    outline: 2px solid #007bff;
}
.gu-transit {
    opacity: 1 !important;
    background-color: #d1ecf1 !important; /* Azul claro */
    border: 2px dashed #0c5460 !important; /* Borde oscuro punteado */
    color: transparent !important; /* Escondemos el texto del hueco para que no distraiga */
    overflow: hidden;
}
.gu-mirror {
    transform: rotate(3deg); /* Un pequeño giro para que se note que flota */
    background-color: white !important;
    box-shadow: 0 10px 20px rgba(0,0,0,0.15);
    cursor: grabbing !important;
    
    position: fixed !important;
    margin: 0 !important;
    z-index: 9999 !important;
    opacity: 0.9;
    
    /* LA CLAVE: El mouse ignora este elemento y detecta lo que hay detrás */
    pointer-events: none !important;
    
}


</style>
<div id="db-wrapper" class="">
    <!-- navbar vertical -->
    <!-- Sidebar -->
    <?php $crum = Menubar::DibujarMenu(); ?>

    <!-- Page Content -->
    <div id="page-content">

        <!-- Page Header -->
        <?php Headerbar::DibujarHeader( ); ?>
            
        <!-- Container fluid -->
        <div class="container-fluid p-4">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12">
                    <div class="border-bottom pb-4 mb-4 d-lg-flex justify-content-between align-items-center">
                        <div class="mb-3 mb-lg-0">
                            <h1 class="mb-0 h2 fw-bold"><?php echo $crum['l2']; ?></h1>

                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="#"><?php echo $crum['l1']; ?></a></li>
                                    <li class="breadcrumb-item active" aria-current="page">
                                        <?php echo $crum['l2']; ?>
                                    </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md-12 col-12">
                    <h4 class="mb-3">Configuraciones de la plataforma</h4>
<?php               if ( $usu->getPerfil_id() == OperacionesCtrl::USUARIOS_PERFIL_SOPORTE || $usu->getPerfil_id() == OperacionesCtrl::USUARIOS_PERFIL_SUPERVISOR ) :?>
                	<div class="row">
                        <div class="col-12 mb-3" >
                        	<div class="alert alert-warning">No tiene configuraciones para ajustar</div>
                        </div>
                    </div>
<?php               endif; ?>
                	
                	<?php if ( $usu->getPerfil_id() == OperacionesCtrl::USUARIOS_PERFIL_SUPER_USUARIO ) :?>
                	<div class="row">
                        <div class="col-12 mb-3" >
                        
                        	<div class="card">
                                <div class="card-header border-bottom-0">
                                    <label for="<?php echo OperacionesCtrl::CFG_ALMACENAMIENTO_TAMANO ?>" class="form-label">
                                        <h5>Tama&ntilde;o almacenamiento</h5>
                                    </label>
                                    <p class="m-0">Cu&aacute;nto espacio en disco se le asigna al cliente</p>
                                </div>

                                <!-- table  -->
                                <div class="card-body pt-2" >
                                    <div class="input-group ">
                                    	<label for="<?php echo OperacionesCtrl::CFG_ALMACENAMIENTO_TAMANO; ?>" class="input-group-text">Tama&ntilde;o de almacenamiento (Gigasbytes)</label>
                                        <input type="text" id="<?php echo OperacionesCtrl::CFG_ALMACENAMIENTO_TAMANO; ?>" value="<?php echo $_CFG_ALMACENAMIENTO_TAMANO; ?>" class="form-control" placeholder="Almacenamiento" aria-label="Almacenamiento" >
                                        <button class="btn btn-outline-primary" type="button" onclick="btnFirmCfgFrm('#<?php echo OperacionesCtrl::CFG_ALMACENAMIENTO_TAMANO; ?>');">Guardar</button>
                                    </div>
                                </div>
                            </div>
                        
                        </div>
                	</div>
                	<?php endif; ?>
                	
                	<?php if ( $usu->getPerfil_id() == OperacionesCtrl::USUARIOS_PERFIL_SUPER_USUARIO ||
                	    $usu->getPerfil_id() == OperacionesCtrl::USUARIOS_PERFIL_ADMINISTRADOR ||
                	    $usu->getPerfil_id() == OperacionesCtrl::USUARIOS_PERFIL_FINANCIERO ) : ?>
                	<div class="row">
                        <div class="col-12 mb-3" >
                        
                        	<div class="card">
                    			<div class="card-body">
                    				<h5 >Est&aacute;ndar deducciones</h5>
                    				<p class="mb-4">Personalice las deducciones que se realizaran a los usuarios</p>
                    				
                    				<div class="row">
                    					<div class="col-12">
                    						
                    						<ul class="nav nav-tabs mb-3" id="pills-tab" role="tablist">
                                                <li class="nav-item" role="presentation">
                                                	<button class="nav-link active" id="pills-crear-tab" data-bs-toggle="pill" data-bs-target="#pills-crear" type="button" role="tab" aria-controls="pills-crear" aria-selected="true">Crear Condiciones</button>
                                                </li>
                                                <li class="nav-item" role="presentation">
                                                	<button class="nav-link" id="pills-guardados-tab" data-bs-toggle="pill" data-bs-target="#pills-guardados" type="button" role="tab" aria-controls="pills-guardados" aria-selected="false" onclick="listarDeducciones( this );">Disponibles</button>
                                                </li>
                                            </ul>
                                            <div class="tab-content" id="pills-tabContent">
                                                <div class="tab-pane fade show active" id="pills-crear" role="tabpanel" aria-labelledby="pills-crear-tab">
                                                	<form id="frmcomp" class="frmcompcls">
                                                    	<div class="row">
                                                    	
                                                    		<div class="col-2 pe-0">
    															<label class="visually-hidden" for="deduc_comparador">Comparador</label>
    															<div class="input-group">
    																<select data-target="#deduc_lbl_valor" data-compare="#deduc_comparador" data-valor="#deduc_valor" data-compare2="#deduc_comparador2" data-valor2="#deduc_valor2" onchange="deducciones.resumen( this );" class="form-select" id="deduc_comparador" name="deduc_comparador">
                                                                        <option disabled selected value="">Seleccione</option>
                                                                        <option value="na">No aplica</option>
                                                                        <option value="menor">&lt;</option>
                                                                        <option value="menorigual">&lt;=</option>
                                                                        <option value="mayor">&gt;</option>
                                                                        <option value="mayorigual">&gt;=</option>
    																</select>
    															</div>
    														</div>
    														<div class="col-3 ps-0">
    															<label class="visually-hidden" for="deduc_valor">Comparador</label>
    															<input data-target="#deduc_lbl_valor" data-compare="#deduc_comparador" data-valor="#deduc_valor" data-compare2="#deduc_comparador2" data-valor2="#deduc_valor2" onkeyup="deducciones.resumen( this );" type="number" id="deduc_valor" name="deduc_valor" class="form-control" aria-label="Monto">
    														</div>
    														
    														<div class="col-2 d-flex justify-content-center align-items-center px-0">
    															<label>Y</label>
    														</div>
    														
    														<div class="col-2 pe-0">
    															<label class="visually-hidden" for="deduc_comparador2">Comparador</label>
    															<div class="input-group">
    																<select data-target="#deduc_lbl_valor" data-compare="#deduc_comparador" data-valor="#deduc_valor" data-compare2="#deduc_comparador2" data-valor2="#deduc_valor2" onchange="deducciones.resumen( this );" class="form-select" id="deduc_comparador2" name="deduc_comparador2">
                                                                        <option disabled selected value="">Seleccione</option>
                                                                        <option value="na">No aplica</option>
                                                                        <option value="menor">&lt;</option>
                                                                        <option value="menorigual">&lt;=</option>
                                                                        <option value="mayor">&gt;</option>
                                                                        <option value="mayorigual">&gt;=</option>
    																</select>
    															</div>
    														</div>
    														<div class="col-3 ps-0">
    															<label class="visually-hidden" for="deduc_valor2">Comparador 2</label>
    															<input data-target="#deduc_lbl_valor" data-compare="#deduc_comparador" data-valor="#deduc_valor" data-compare2="#deduc_comparador2" data-valor2="#deduc_valor2" onkeyup="deducciones.resumen( this );" type="number" id="deduc_valor2" name="deduc_valor2" class="form-control" aria-label="Monto">
    														</div>
                                                    		
                                                    		<div id="deduc_lbl_valor" class="col-12 text-muted fs-6 mt-1 mb-2">&nbsp;</div>
                                                    	</div>
                                                    	
                                                    	<div class="row">
                                                			<div id="frmcuarto" class="row mb-3" ></div>
    														<div class="d-grid gap-2">
    															<button data-target="#frmcuarto" onclick="deducciones.agregar_click( this );" class="btn btn-secondary" type="button">Agregar deducci&oacute;n</button>
    															<button id="btndeducGuardar" data-formcls="frmcompcls" data-firma="#deduc_lbl_valor" data-modificar="false" onclick="btnDeduccionGuardar( this );" class="btn btn-primary" type="button">Guardar deducciones</button>
    															<button id="btndeducModificar" data-formcls="frmcompcls" data-firma="#deduc_lbl_valor" data-modificar="true" onclick="btnDeduccionGuardar( this );" class="btn btn-primary btnsMods" type="button" style="display: none;">Modificar deducciones</button>
    															<button id="btndeducCancelar" data-modificar="false" onclick="btnDeducCancelar( this );" class="btn btn-danger" type="button" style="display: none;">Cancelar Cambio</button>
    														</div>
                                                    	</div>
                                                	</form>
                                                </div>
                                                <div class="tab-pane fade" id="pills-guardados" role="tabpanel" aria-labelledby="pills-guardados-tab">
                                                	<div class="row" id="contTb">
                                                    	<div class="col-3">
                                                        	<div class="d-flex align-items-center">
                                                              <strong>Loading...</strong>
                                                              <div class="spinner-border spinner-border-sm ms-auto" role="status" aria-hidden="true"></div>
                                                            </div>
                                                    	</div>
                                                    </div>
                                                </div>
                                            </div>
                    					</div>
                    				</div>
                    				
                    			</div>
                    		</div>
                        
                        </div>
                    </div>
                    
                	<div class="row">
                        <div class="col-12 mb-3" >
                        
                        	<div class="card">
                    			<div class="card-body">
                    				<h5 >Maestra de descuentos</h5>
                    				<p class="mb-4">Ingrese los registros de la tabla de porcentajes de descuentos y sus descripciones</p>
                    				
                    				<div class="row">
                    					<div id="tbMasterCont" class="col-12" ></div>
                					</div>
            					</div>
        					</div>
    					</div>
					</div>
                    <?php endif; ?>

                </div>

            </div>

        </div>

    </div>
</div>

<script type="application/javascript" src="./temas/js/DataTables/datatables.min.js"></script>

<script type="application/javascript">
<?php // TODO: Tarea 147 - Crea una clase en front que permite controlar las tareas de la la Maestra de descuentos ?>
const GestionDataTable = function(instancia, containerId, columnasIniciales) {
    const self = this;
    let table = null;
    let tableId = "tbJson_" + ut.GetUUID();
    
    let rowGlb;
    let currentData = [];
    
    self.datos = [];

    self.init = function() {
    	/*
        let html = `
            <div class="dt-buttons-container" style="margin-bottom:15px;">
                <button type="button" class="btn btn-primary btn-sm btn-nuevo-${tableId}">Nuevo Registro</button>
                <button type="button" class="btn btn-primary btn-sm btn-guardar-${tableId}">Guardar</button>
                <input type="file" class="file-import-${tableId}" style="display:none" accept=".json">
                <button type="button" onclick="jQuery('.file-import-${tableId}').click()">Importar JSON</button>
            </div>
            <div class="table-responsive-custom">
            	<table id="${tableId}" class="table table-sm table-bordered table-striped table-hover responsive display" style="width:100%"></table>
            </div>
        `;
        */
        let html = `
            <div class="dt-buttons-container" style="margin-bottom:15px;">
                <button type="button" class="btn btn-primary btn-sm btn-nuevo-${tableId}">Nuevo Registro</button>
                <button type="button" class="btn btn-primary btn-sm btn-guardar-${tableId}">Guardar</button>
                <button type="button" class="btn btn-primary btn-sm btn-lista-${tableId}">Items grupo</button>
            </div>
            <div class="table-responsive-custom">
            	<table id="${tableId}" class="table table-sm table-bordered table-striped table-hover responsive display" style="width:100%"></table>
            </div>
        `;
        
        jQuery(containerId).html(html);

        table = jQuery(`#${tableId}`).DataTable({
            data: self.datos,
            columns: [
                ...columnasIniciales,
                {
                    title: "Acciones",
                    data: null,
                    width: 30,
                    render: function() {
                        return `
                            <button class="btn m-0 px-1 py-0 text-muted text-primary-hover texttooltip btn-edit-row" data-template="btnEditTpl-${tableId}">
                            	<i class="fe fe-edit fs-5"></i>
                            	<div id="btnEditTpl-${tableId}" class="d-none">
                            		<h6 class="mb-0 text-white">Editar</h6>
                            	</div>
                            </button>
                            <button class="btn m-0 px-1 py-0 text-muted text-primary-hover ms-0 texttooltip btn-delete-row" data-template="btnDelTpl-${tableId}">
                            	<i class="fe fe-trash-2 fs-5"></i>
                            	<div id="btnDelTpl-${tableId}" class="d-none">
                            		<h6 class="mb-0 text-white">Eliminar</h6>
                            	</div>
                            </button>
                        `;
                    }
                }
            ],
            order: [[5, 'desc']],
            responsive: false,
            language: lengua_es,
        });

        self.bindEvents();
    };
    
    self.getData = function( d ){
    	const fn = d['fn'];
        const form_data = new FormData();
        form_data.append('ajax', '<?php echo md5(IndexCtrl::API_MaestrasVirtualGet); ?>');
    
        __TransportarData(
            form_data,
            function( oDt ) {
            	try {
                    const json = JSON.parse( ut.b64DecodeUnicode( oDt ) );
                    table.clear().rows.add(json).draw();
                    self.actualizarEstado();
                } catch (err) {
                    console.error("Error al cargar JSON", err);
                }
            	fn( oDt );
            },
            function ( err ) {
                const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
                const alerta = jQuery(objmdlErr + ' div.alert');
                alerta.attr('class','alert alert-danger');
                alerta.html( err.responseText );
    
                jQuery( objmdlErr ).modal('show');
            }
        );
    };
    
    self.setFieldData = function(){
    	ut.validarFrm( 'formmaestraCls' + tableId , function (r) {
    		currentData.grupo = r['maestra-grupo-' + tableId ];
    		currentData.cod_interno = r['maestra-cod_interno-' + tableId ];
    		currentData.cod_desc = r['maestra-cod_desc-' + tableId ];
    		currentData.porcentaje = r['maestra-porcentaje-' + tableId ];
    		
            rowGlb.data(currentData).draw();
            self.actualizarEstado();
    	});
    };
    
    self.grpItems_Eliminar = function( o ){
    	const _o = jQuery( o );
    	const dt = _o.data();
    	
    	const li = jQuery( dt['li'] );
    	const ul = jQuery( dt['ul'] );
    	
    	if( confirm( "Desea eliminar este registro?" ) ){
    		li.hide("fast", function(){
    			li.remove();
    			
    			const estanuevo = ul.find('li');
    			if( estanuevo.length == 0 ){
            		ul.html( '<li class="list-group-item estanuevo">No hay items</li>' );
            	}
    		});
    	}
    };
    
    self.grpItems_GuardarLista = function( o ){
    	const _o = jQuery( o );
    	const dt = _o.data();
    	
    	_o.attr( "disabled", "disabled" );
    	_o.html( validadorGlob.ajaxspinner() );
    	
    	const lis = jQuery( dt['ul'] );
    	
    	const data = [];
    	
    	lis.find( 'li' ).each(function(i,obj){
    		const _obj = jQuery( obj );
    		const dtObj = _obj.data();
    		data.push( dtObj['value'] );
    	});
    	
    	const blob = JSON.stringify( data );
        const dt64 = ut.b64EncodeUnicode( blob );
		
		const form_data = new FormData();
        form_data.append('ajax', '<?php echo md5(IndexCtrl::API_MaestrasGrpVirtualAdd ); ?>' );
        form_data.append('vl', dt64 );
    
        __TransportarData(
            form_data,
            function( oDt ) {
            	_o.removeAttr( "disabled" );
    			_o.html( "Guardar" );
            },
            function ( err ) {
                const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
                const alerta = jQuery(objmdlErr + ' div.alert');
                alerta.attr('class','alert alert-danger');
                alerta.html( err.responseText );
    
                jQuery( objmdlErr ).modal('show');
            }
        );
        
    };
    
    const grpItemsTpl = function( txt, target ){
		const firma = ut.b64EncodeUnicode( ( "" + txt ).toLowerCase() ).replace(/==/ig, "").replace(/=/ig, "");
		
		const liId = 'li-' + firma;
		
		const htmlli = [];
		
    	htmlli.push( '<li id="' + liId + '" data-value="' + txt + '" class="list-group-item d-flex justify-content-between align-items-center" >' );
    	htmlli.push( '	<div class="d-flex align-items-center" >' );
    	htmlli.push( '		' + txt + '' );
    	htmlli.push( '	</div>' );
    	htmlli.push( '	<div >' );
    	htmlli.push( '		<button data-ul="#' + target.attr('id') + '" data-li="#' + liId + '" class="btn-close" aria-label="Close" onclick="' + instancia + '.grpItems_Eliminar( this );"></button>' );
    	htmlli.push( '	</div>' );
    	htmlli.push( '</li>' );
    	
    	return { "id" : liId, "html" : htmlli.join('') }
    };
    
    self.grpItems_Agregar = function( o ){
    	const _o = jQuery( o );
    	const dt = _o.data();
    	
    	const target = jQuery( dt['target'] );
    	const valor = jQuery( dt['valor'] );
    	
    	ut.validarFrm( 'formmaestraItemGrpCls' + tableId, function (r) {
    	
			const txt = jQuery.trim( valor.val() );
    	
        	if( txt != null && ("" + txt ).length > 0 ){
    			const estanuevo = target.find('.estanuevo');
    			
    			const obLi = grpItemsTpl( txt, target );
    			const liId = obLi['id'];
    			const unicoItem = target.find( '#' + liId );
    			
    			if( unicoItem.length ) {
    				alert('El registro ya existe');
    			}
    			else{
    				const htmlli = [];
                	htmlli.push( '<li id="' + liId + '" data-value="' + txt + '" class="list-group-item d-flex justify-content-between align-items-center" >' );
                	htmlli.push( '	<div class="d-flex align-items-center" >' );
                	htmlli.push( '		' + txt + '' );
                	htmlli.push( '	</div>' );
                	htmlli.push( '	<div >' );
                	htmlli.push( '		<button data-ul="#' + target.attr('id') + '" data-li="#' + liId + '" class="btn-close" aria-label="Close" onclick="' + instancia + '.grpItems_Eliminar( this );"></button>' );
                	htmlli.push( '	</div>' );
                	htmlli.push( '</li>' );
                	
                	if( estanuevo.length ){
                		target.html( obLi['html'] );
                	}
                	else{
                		target.append( obLi['html'] );
                	}
                	
                	agregarAgarre( { "contenedor" : target.attr('id'), "hijos": 'list-group-item' } );
                	
    			}
        	
        	}
    	
    	});
    };
    
    self.bindEvents = function() {
        jQuery(`#${tableId} tbody`).on('click', '.btn-delete-row', function() {
        
        	if(	confirm('Desea eliminar este registro?') ){
        		table.row(jQuery(this).parents('tr')).remove().draw();
            	self.actualizarEstado();
        	}
        
        });

        jQuery(`#${tableId} tbody`).on('click', '.btn-edit-row', function() {
            rowGlb = table.row(jQuery(this).parents('tr'));
            currentData = rowGlb.data();
            
            const modalId = 'stcMdl-' + tableId;
            if( jQuery( "#" + modalId ).length ){
            	modalId.remove();
            }
            
            const modalHtml = [];
            modalHtml.push('<div class="modal fade" id="stcMdl-' + tableId + '" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="stcBLabel' + tableId + '" aria-hidden="true">');
			modalHtml.push('	<div class="modal-dialog">');
			modalHtml.push('		<div class="modal-content">');
			modalHtml.push('			<div class="modal-header">');
			modalHtml.push('				<h5 class="modal-title" id="stcBLabel' + tableId + '">Registro</h5>');
			modalHtml.push('				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>');
			modalHtml.push('			</div>');
			modalHtml.push('			<div class="modal-body">');
			
			modalHtml.push('				<form id="formmaestra' + tableId + '" class="formmaestraCls' + tableId + '">');
			modalHtml.push('					<div class="form-floating mb-3">');
			modalHtml.push('						<input type="text" class="form-control" id="maestra-grupo-' + tableId + '" name="maestra-grupo-' + tableId + '" placeholder="grupo">');
			modalHtml.push('						<label for="maestra-grupo-' + tableId + '">Grupo</label>');
			modalHtml.push('					</div>');
			
			modalHtml.push('					<div class="form-floating mb-3">');
			modalHtml.push('						<input required="required" type="text" class="form-control" id="maestra-cod_interno-' + tableId + '" name="maestra-cod_interno-' + tableId + '" placeholder="0000">');
			modalHtml.push('						<label for="maestra-cod_interno-' + tableId + '">C&oacute;digo interno</label>');
			modalHtml.push('					</div>');
			
			modalHtml.push('					<div class="form-floating mb-3">');
			modalHtml.push('						<input required="required" type="text" class="form-control" id="maestra-cod_desc-' + tableId + '" name="maestra-cod_desc-' + tableId + '" placeholder="Descripci&oacute;n">');
			modalHtml.push('						<label for="maestra-cod_desc-' + tableId + '">Descripci&oacute;n c&oacute;digo</label>');
			modalHtml.push('					</div>');
			
			modalHtml.push('					<div class="form-floating mb-3">');
			modalHtml.push('						<input required="required" type="number" class="form-control" id="maestra-porcentaje-' + tableId + '" name="maestra-porcentaje-' + tableId + '" placeholder="0.0" step="any">');
			modalHtml.push('						<label for="maestra-porcentaje-' + tableId + '">Porcentaje</label>');
			modalHtml.push('					</div>');
			modalHtml.push('				</form>');
			
			modalHtml.push('			</div>');
			modalHtml.push('			<div class="modal-footer">');
			modalHtml.push('				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>');
			modalHtml.push('				<button onclick="' + instancia + '.setFieldData();" type="button" class="btn btn-primary">Guardar</button>');
			modalHtml.push('			</div>');
			modalHtml.push('		</div>');
			modalHtml.push('	</div>');
			modalHtml.push('</div>');
            
            const mdl = jQuery( modalHtml.join('') );
            mdl.modal('show');
        });
        jQuery(`.btn-nuevo-${tableId}`).on('click', function() {
        	const fData = ictrl.getFormattedDate();
        	
            const nuevoObj = { id: ut.GetUUID(), grupo: "grp", cod_interno: "0000", cod_desc: "Descripci&oacute;n", porcentaje: "0.0", fecha: fData, creador: "<?php echo $usu->getNombres() . " " . $usu->getApellidos() ?>" };
            table.row.add(nuevoObj).draw();
            self.actualizarEstado();
        });

        jQuery(`.btn-guardar-${tableId}`).on('click', function() {
			const opc = { 'id' : 'ajaxldr','size' : 'modal-sm' };
            const objmdl = mngModal.dibujar( opc );
            jQuery( objmdl ).modal('show');
            
            const data = table.rows().data().toArray();
            const blob = JSON.stringify( data );
            const dt64 = ut.b64EncodeUnicode( blob );
            
            const form_data = new FormData();
            form_data.append('ajax', '<?php echo md5(IndexCtrl::API_MaestrasVirtualAdd ); ?>');
            form_data.append('vl', dt64);
        
            __TransportarData(
                form_data,
                function( o ) {
                    setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
                },
                function ( err ) {
                    const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
                    const alerta = jQuery(objmdlErr + ' div.alert');
                    alerta.attr('class','alert alert-danger');
                    alerta.html( err.responseText );
        
                    jQuery( objmdlErr ).modal('show');
                    setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
                }
            );
        });

    	jQuery(`.btn-lista-${tableId}`).on('click', function() {
    		const frmId = 'formmaestraItemGrp' + tableId;
    		const ulId = 'maestra-listGrp-' + tableId ;
    		const idItemVacio = 'maestra-itemEmpty-' + tableId ;
    		
    		const modalId = 'stcMdlItemsGrp-' + tableId;
    		if( jQuery( "#" + modalId ).length ){
    			jQuery( "#" + modalId ).remove();
    		}
    		
            const modalHtml = [];
            modalHtml.push('<div class="modal fade" id="stcMdlItemsGrp-' + tableId + '" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="stcItemsBLabel' + tableId + '" aria-hidden="true">');
			modalHtml.push('	<div class="modal-dialog modal-lg modal-dialog-scrollable">');
			modalHtml.push('		<div class="modal-content">');
			modalHtml.push('			<div class="modal-header">');
			modalHtml.push('				<h5 class="modal-title" id="stcItemsBLabel' + tableId + '">Items del grupo</h5>');
			modalHtml.push('				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>');
			modalHtml.push('			</div>');
			modalHtml.push('			<div class="modal-body">');
			
			modalHtml.push('				<form id="' + frmId + '" class="formmaestraItemGrpCls' + tableId + ' d-flex bd-highlight">');
			modalHtml.push('					<div class="form-floating mb-3 flex-grow-1 bd-highlight">');
			modalHtml.push('						<input required="required" type="text" class="form-control" id="maestra-itemgrupo-' + tableId + '" name="maestra-itemgrupo-' + tableId + '" placeholder="item nuevo">');
			modalHtml.push('						<label for="maestra-itemgrupo-' + tableId + '">Grupo</label>');
			modalHtml.push('					</div>');
			
			modalHtml.push('					<div class="bd-highlight ms-3">');
			modalHtml.push('						<button data-valor="#maestra-itemgrupo-' + tableId + '" data-target="#maestra-listGrp-' + tableId + '" onclick="' + instancia + '.grpItems_Agregar( this );" type="button" class="btn btn-primary" >');
			modalHtml.push('							Agregar item');
			modalHtml.push('						</button>');
			modalHtml.push('					</div>');
			
			modalHtml.push('				</form>');
			
			modalHtml.push('				<div class="card shadow-lg" style="">');
			modalHtml.push('					<div class="card-header">');
			modalHtml.push('						<h5>Items existentes</h5>');
			modalHtml.push('					</div>');
			modalHtml.push('					<div class="card-body">');
			modalHtml.push('						<ul id="' + ulId + '" class="list-group">');
			modalHtml.push('							<li id="' + idItemVacio + '" class="list-group-item estanuevo">' + validadorGlob.ajaxspinner() + '</li>');
			modalHtml.push('						<ul >');
			modalHtml.push('					</div>');
			modalHtml.push('				</div >');
			
			modalHtml.push('			</div>');
			modalHtml.push('			<div class="modal-footer">');
			modalHtml.push('				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>');
			modalHtml.push('				<button data-ul="#' + ulId + '" onclick="' + instancia + '.grpItems_GuardarLista( this );" type="button" class="btn btn-primary">Guardar</button>');
			modalHtml.push('			</div>');
			modalHtml.push('		</div>');
			modalHtml.push('	</div>');
			modalHtml.push('</div>');
            
            const mdl = jQuery( modalHtml.join('') );
            mdl.modal('show');
            
			const form_data = new FormData();
            form_data.append('ajax', '<?php echo md5(IndexCtrl::API_MaestrasGrpVirtualGet ); ?>');
        
            __TransportarData(
                form_data,
                function( oR ) {
                	const oDt = JSON.parse( ut.b64DecodeUnicode( oR ) );
                	
                	if( oDt.length > 0 ){
                		const htmltmp = [];
                		for (const ind in oDt ) {
                        	if ( Object.hasOwnProperty.call( oDt, ind ) ) {
                        		const _el = oDt[ ind ];
                        		const oItem = grpItemsTpl( _el, jQuery( ulId ) );
                        		htmltmp.push( oItem['html'] );
                    		}
                		}
                		jQuery("#" + ulId).html( htmltmp.join('') );
                		agregarAgarre( { "contenedor" : ulId, "hijos": 'list-group-item' } );
                	}
                	else{
                		jQuery( "#" + ulId ).html('No hay items');
                	}
                },
                function ( err ) {
                    const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
                    const alerta = jQuery(objmdlErr + ' div.alert');
                    alerta.attr('class','alert alert-danger');
                    alerta.html( err.responseText );
        
                    jQuery( objmdlErr ).modal('show');
                    setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
                }
            );
            
            mdl.find( '#' + frmId ).on('submit', function(e) {
                e.preventDefault();
                
                const idBtnTmp = 'btnAddItemTrigger-' + tableId;
                if( jQuery( "#" + idBtnTmp ).length ){
                	jQuery( "#" + idBtnTmp ).remove();
                }
                
                const btnTmp = '<button id="' + idBtnTmp + '" data-valor="#maestra-itemgrupo-' + tableId + '" data-target="#maestra-listGrp-' + tableId + '" ><button>'; 
                self.grpItems_Agregar( jQuery( btnTmp ) );
                return false;
            });
            
    	});
    	
        jQuery(`.file-import-${tableId}`).on('change', function(e) {
            const file = e.target.files[0];
            if (!file) return;

            const reader = new FileReader();
            reader.onload = function(evt) {
                try {
                    const json = JSON.parse(evt.target.result);
                    table.clear().rows.add(json).draw();
                    self.actualizarEstado();
                } catch (err) {
                    console.error("Error al cargar JSON", err);
                }
            };
            reader.readAsText(file);
        });
        
    };

    self.actualizarEstado = function() {
        self.datos = table.rows().data().toArray();
        // Aquí podrías disparar self.instanceNameCtrlCambios si existe
    };
};
</script>

<script type="application/javascript">
<?php 
/*
 * @yalfonso
 * TODO: Tarea 20 - Crear m&eacute;todo que guarda la configuraci&oacute;n global de los perfiles de contabilidad
 */
?>
const btnDeduccionGuardar = function( o ){
	deducciones.guardar_click( o , function(){
		jQuery('#pills-guardados-tab').trigger('click');
		jQuery('#frmcuarto').html('');
		document.getElementById('frmcomp').reset();
		jQuery('#deduc_comparador,#deduc_valor,#deduc_comparador2,#deduc_valor2').prop('disabled', false);
	});
};
<?php 
/*
 * @yalfonso
 * TODO: Tarea 21 - Crear m&eacute;todo que modifica la configuraci&oacute;n global de los perfiles de contabilidad
 */
?>
const btnDeduccionEditar = function( o ){
	jQuery( o ).attr('data-target', '#frmcuarto');
	deducciones.editar_click( o , function( dt ){
		jQuery('#pills-crear-tab').tab('show');
		jQuery('#frmcuarto').html('');
		document.getElementById('frmcomp').reset();
		jQuery('#deduc_comparador,#deduc_valor,#deduc_comparador2,#deduc_valor2').prop('disabled', true);
		jQuery('#btndeducModificar, #btndeducCancelar').show('fast');
		jQuery('#btndeducGuardar').hide('fast');
	});
};

const btnDeducCancelar = function( o ){
	jQuery('#frmcuarto, #deduc_lbl_valor').html('');
	document.getElementById('frmcomp').reset();
	jQuery('#deduc_comparador,#deduc_valor,#deduc_comparador2,#deduc_valor2').prop('disabled', false);
	jQuery('#btndeducModificar, #btndeducCancelar').fadeOut('fast');
	jQuery('#btndeducGuardar').show('fast');
};
<?php 
/*
 * @yalfonso
 * TODO: Tarea 22 - Crear m&eacute;todo lista las posibles deducciones que aplican para el usuario que radica cuenta de cobro
 */
?>
const listarDeducciones = function(){
    const opc = { 'id' : 'ajaxldr','size' : 'modal-sm' };
    const objmdl = mngModal.dibujar( opc );
    jQuery( objmdl ).modal('show');
    
    const form_data = new FormData();
    form_data.append('ajax', '<?php echo md5( IndexCtrl::API_DeduccionesVirtualGetAjax ); ?>');
    
    __TransportarData(
        form_data,
        function( o ) {
        	deducciones.dibujarDataTable( { 'contenedor' : '#contTb', 'data' : o , 'editar' : 'btnDeduccionEditar' } );
        	setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
        },
        function ( err ) {
        	const oErr = err.responseJSON;
            const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
            const alerta = jQuery(objmdlErr + ' div.alert');
            alerta.attr('class','alert alert-danger');
            alerta.html( oErr['msj'] );
    
            jQuery( objmdlErr ).modal('show');
            setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
        }
    );
};


/**
 * Configura y controla el comportamiento del botón "Firmar" en el formulario.
 *
 * @param {Object} o Parámetros y estado necesarios para la configuración del botón.
 * @return void
 */
const btnFirmCfgFrm = function( o ){
    const opc = { 'id' : 'ajaxldr','size' : 'modal-sm' };
    const objmdl = mngModal.dibujar( opc );
    jQuery( objmdl ).modal('show');

    var _o = jQuery( o );
    var id = _o.attr('id');
    var vl = null;
    if( (""+_o.attr('type')).toLowerCase() == "checkbox" ){
    	vl = _o.is(':checked');
    }
    else{
    	vl = _o.val();
    }

    const form_data = new FormData();
    form_data.append('id', id);
    form_data.append('vl', vl);
    form_data.append('ufull', '<?php echo $usu->getNombres() . " " . $usu->getApellidos(); ?>');
    form_data.append('ajax', '<?php echo md5(IndexCtrl::API_AgregarConfigCorp); ?>');

    __TransportarData(
        form_data,
        function( o ) {
            setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
        },
        function ( err ) {
            const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
            const alerta = jQuery(objmdlErr + ' div.alert');
            alerta.attr('class','alert alert-danger');
            alerta.html( err.responseText );

            jQuery( objmdlErr ).modal('show');
            setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
        }
    );
    
};

let miGestion;
let deducciones;

jQuery( document ).ready(function(){
	deducciones = new Deducciones();
	
    const misColumnas = [
        { title: "ID", data: "id", width: 300 },
        { title: "Grupo", data: "grupo" },
        { title: "C&oacute;digo interno", data: "cod_interno" },
        { title: "Descripci&oacute;n c&oacute;digo", data: "cod_desc" },
        { title: "%", data: "porcentaje" },
        { title: "Fecha", data: "fecha", width: 150 },
        { title: "Creador", data: "creador", width: 150 }
    ];
    
    miGestion = new GestionDataTable("miGestion", "#tbMasterCont", misColumnas);
    miGestion.init();
    miGestion.getData( { 
    	fn : function( oDt ){
    	} 
    });
	
});
</script>