<?php
use src\sistema\Menubar\Menubar;
use src\sistema\Headerbar\Headerbar;

$cfg = OperacionesCtrl::LeerConfigCorp();

// Almacenamiento
$_CFG_ALMACENAMIENTO_TAMANO = intval( isset( $cfg[ OperacionesCtrl::CFG_ALMACENAMIENTO_TAMANO ]) ? $cfg[ OperacionesCtrl::CFG_ALMACENAMIENTO_TAMANO ]["val"] : '5' );

// Deducciones
//$_CFG_DEDUCCIONES_DATA = intval( isset( $cfg[ OperacionesCtrl::CFG_DEDUCCIONES_DATA ]) ? $cfg[ OperacionesCtrl::CFG_DEDUCCIONES_DATA ]["val"] : base64_encode( '[]' ) );

$usu = null;
if ( Seguridad::isLogin() ) {
    $usu = $_SESSION["usu"];
}

$filtroUsr = array(
    'perfil_id' => array(
        OperacionesCtrl::USUARIOS_PERFIL_ADMINISTRADOR,
        OperacionesCtrl::USUARIOS_PERFIL_FINANCIERO,
        OperacionesCtrl::USUARIOS_PERFIL_SUPERVISOR,
        OperacionesCtrl::USUARIOS_PERFIL_SUPERVISORADM,
        OperacionesCtrl::USUARIOS_PERFIL_API
        //,OperacionesCtrl::USUARIOS_PERFIL_SUPER_USUARIO
    )
);

$d_usuarios = null;
try {
    $d_usuarios = OperacionesCtrl::usuarios_Obtener( $filtroUsr );
} catch (\Throwable $th) {
    throw new \Exception( $th->getMessage() );
}

$d_tpls = array();
try {
    $d_tpls = OperacionesCtrl::editarPlantillas_Obtener( array() );
} catch (\Throwable $th) {
    throw new \Exception( $th->getMessage() );
}

$d_json_campos = [];
try {
    $d_json_campos = OperacionesCtrl::formularios_Obtener( [ 'w_json_all' => true ] );
} catch (\Throwable $th) {
    throw new \Exception( $th->getMessage() );
}

$d_json = [];
foreach ( $d_json_campos as $kJs ) {
    $objson = json_decode( $kJs['json'], true );
    $cfgdt = [ "arreglo" => $objson, "campo" => "staticfield" ];
    $d_json[ $kJs['id'] ] = OperacionesCtrl::formularios_Helper_buscarValoresCampo( $cfgdt );
}

$defReflista = [];
$reflista = OperacionesCtrl::reflista_Obtener( [] );
foreach ( $reflista as $kRl) {
    if( !( $kRl['nombre'] == "[formulario]" ) ){
        $defReflista[] = $kRl['nombre'];
    }
}
$d_json[ 'reflista' ] = $defReflista;
?>
<style>
/* Asegura que el contenedor permita el scroll */
.table-responsive-custom {
    width: 100%;
    overflow-x: auto;
    -webkit-overflow-scrolling: touch; /* Suavidad en móviles */
    margin-bottom: 1rem;
}

/* Evita que el texto de las celdas se amontone, forzando el scroll */
table.dataTable.nowrap th, 
table.dataTable.nowrap td {
    white-space: nowrap;
}


.gu-mirror.d-flex {
    display: flex !important;
}

.gu-over {
    background-color: rgba(0, 123, 255, 0.05) !important;
    outline: 2px solid #007bff;
}
.gu-transit {
    opacity: 1 !important;
    background-color: #d1ecf1 !important; /* Azul claro */
    border: 2px dashed #0c5460 !important; /* Borde oscuro punteado */
    color: transparent !important; /* Escondemos el texto del hueco para que no distraiga */
    overflow: hidden;
}
.gu-mirror {
    transform: rotate(3deg); /* Un pequeño giro para que se note que flota */
    background-color: white !important;
    box-shadow: 0 10px 20px rgba(0,0,0,0.15);
    cursor: grabbing !important;
    
    position: fixed !important;
    margin: 0 !important;
    z-index: 9999 !important;
    opacity: 0.9;
    
    /* LA CLAVE: El mouse ignora este elemento y detecta lo que hay detrás */
    pointer-events: none !important;
    
    padding: 0px 10px;
}

.draggable { 
    display: inline-block; 
    padding: 6px 12px; 
    margin: 5px; 
    background-color: #f8f9fa; 
    border: 1px solid #ced4da; 
    border-radius: 4px; 
    cursor: grab; 
} 
.dropzone { 
    min-height: 80px;
    border: 2px dashed #c6d7a4;
    padding: 10px;
    background-color: #f8fff5; 
}
.dropzone div{
    border: dashed 2px #d1d1d1;
    padding: 16px 16px;
    background-color: #fbfbfb;
    margin-right: 1px;
}
#operators div{
    border: solid 1px #d1d1d1;
    margin: 0px 3px 3px 0px;
    padding: 0px 10px;
}
</style>

</style>
<div id="db-wrapper" class="">
    <!-- navbar vertical -->
    <!-- Sidebar -->
    <?php $crum = Menubar::DibujarMenu(); ?>

    <!-- Page Content -->
    <div id="page-content">

        <!-- Page Header -->
        <?php Headerbar::DibujarHeader( ); ?>
            
        <!-- Container fluid -->
        <div class="container-fluid p-4">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12">
                    <div class="border-bottom pb-4 mb-4 d-lg-flex justify-content-between align-items-center">
                        <div class="mb-3 mb-lg-0">
                            <h1 class="mb-0 h2 fw-bold"><?php echo $crum['l2']; ?></h1>

                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="#"><?php echo $crum['l1']; ?></a></li>
                                    <li class="breadcrumb-item active" aria-current="page">
                                        <?php echo $crum['l2']; ?>
                                    </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md-12 col-12">
                    <h4 class="mb-3">Configuraciones de la plataforma</h4>
<?php               if ( $usu->getPerfil_id() == OperacionesCtrl::USUARIOS_PERFIL_SOPORTE || $usu->getPerfil_id() == OperacionesCtrl::USUARIOS_PERFIL_SUPERVISOR ) :?>
                	<div class="row">
                        <div class="col-12 mb-3" >
                        	<div class="alert alert-warning">No tiene configuraciones para ajustar</div>
                        </div>
                    </div>
<?php               endif; ?>
                	
                	<?php if ( $usu->getPerfil_id() == OperacionesCtrl::USUARIOS_PERFIL_SUPER_USUARIO ) :?>
                	<div class="row">
                        <div class="col-12 mb-3" >
                        
                        	<div class="card">
                                <div class="card-header border-bottom-0">
                                    <label for="<?php echo OperacionesCtrl::CFG_ALMACENAMIENTO_TAMANO ?>" class="form-label">
                                        <h5>Tama&ntilde;o almacenamiento</h5>
                                    </label>
                                    <p class="m-0">Cu&aacute;nto espacio en disco se le asigna al cliente</p>
                                </div>

                                <!-- table  -->
                                <div class="card-body pt-2" >
                                    <div class="input-group ">
                                    	<label for="<?php echo OperacionesCtrl::CFG_ALMACENAMIENTO_TAMANO; ?>" class="input-group-text">Tama&ntilde;o de almacenamiento (Gigasbytes)</label>
                                        <input type="text" id="<?php echo OperacionesCtrl::CFG_ALMACENAMIENTO_TAMANO; ?>" value="<?php echo $_CFG_ALMACENAMIENTO_TAMANO; ?>" class="form-control" placeholder="Almacenamiento" aria-label="Almacenamiento" >
                                        <button class="btn btn-outline-primary" type="button" onclick="btnFirmCfgFrm('#<?php echo OperacionesCtrl::CFG_ALMACENAMIENTO_TAMANO; ?>');">Guardar</button>
                                    </div>
                                </div>
                            </div>
                        
                        </div>
                	</div>
                	<?php endif; ?>
                	
                	<?php if ( $usu->getPerfil_id() == OperacionesCtrl::USUARIOS_PERFIL_SUPER_USUARIO ||
                	    $usu->getPerfil_id() == OperacionesCtrl::USUARIOS_PERFIL_ADMINISTRADOR ||
                	    $usu->getPerfil_id() == OperacionesCtrl::USUARIOS_PERFIL_FINANCIERO ) : ?>
                	<div class="row">
                        <div class="col-12 mb-3" >
                        
                        	<div class="card">
                    			<div class="card-body">
                    				<h5 >Est&aacute;ndar deducciones</h5>
                    				<p class="mb-4">Personalice las deducciones que se realizaran a los usuarios</p>
                    				
                    				<div class="row">
                    					<div class="col-12">
                    						
                    						<ul class="nav nav-tabs mb-3" id="pills-tab" role="tablist">
                                                <li class="nav-item" role="presentation">
                                                	<button class="nav-link active" id="pills-crear-tab" data-bs-toggle="pill" data-bs-target="#pills-crear" type="button" role="tab" aria-controls="pills-crear" aria-selected="true">Crear Condiciones</button>
                                                </li>
                                                <li class="nav-item" role="presentation">
                                                	<button class="nav-link" id="pills-guardados-tab" data-bs-toggle="pill" data-bs-target="#pills-guardados" type="button" role="tab" aria-controls="pills-guardados" aria-selected="false" onclick="listarDeducciones( this );">Disponibles</button>
                                                </li>
                                            </ul>
                                            <div class="tab-content" id="pills-tabContent">
                                                <div class="tab-pane fade show active" id="pills-crear" role="tabpanel" aria-labelledby="pills-crear-tab">
                                                	<form id="frmcomp" class="frmcompcls">
                                                    	<div class="row">
                                                    	
                                                    		<div class="col-2 pe-0">
    															<label class="visually-hidden" for="deduc_comparador">Comparador</label>
    															<div class="input-group">
    																<select data-target="#deduc_lbl_valor" data-compare="#deduc_comparador" data-valor="#deduc_valor" data-compare2="#deduc_comparador2" data-valor2="#deduc_valor2" onchange="deducciones.resumen( this );" class="form-select" id="deduc_comparador" name="deduc_comparador">
                                                                        <option disabled selected value="">Seleccione</option>
                                                                        <option value="na">No aplica</option>
                                                                        <option value="menor">&lt;</option>
                                                                        <option value="menorigual">&lt;=</option>
                                                                        <option value="mayor">&gt;</option>
                                                                        <option value="mayorigual">&gt;=</option>
    																</select>
    															</div>
    														</div>
    														<div class="col-3 ps-0">
    															<label class="visually-hidden" for="deduc_valor">Comparador</label>
    															<input data-target="#deduc_lbl_valor" data-compare="#deduc_comparador" data-valor="#deduc_valor" data-compare2="#deduc_comparador2" data-valor2="#deduc_valor2" onkeyup="deducciones.resumen( this );" type="number" id="deduc_valor" name="deduc_valor" class="form-control" aria-label="Monto">
    														</div>
    														
    														<div class="col-2 d-flex justify-content-center align-items-center px-0">
    															<label>Y</label>
    														</div>
    														
    														<div class="col-2 pe-0">
    															<label class="visually-hidden" for="deduc_comparador2">Comparador</label>
    															<div class="input-group">
    																<select data-target="#deduc_lbl_valor" data-compare="#deduc_comparador" data-valor="#deduc_valor" data-compare2="#deduc_comparador2" data-valor2="#deduc_valor2" onchange="deducciones.resumen( this );" class="form-select" id="deduc_comparador2" name="deduc_comparador2">
                                                                        <option disabled selected value="">Seleccione</option>
                                                                        <option value="na">No aplica</option>
                                                                        <option value="menor">&lt;</option>
                                                                        <option value="menorigual">&lt;=</option>
                                                                        <option value="mayor">&gt;</option>
                                                                        <option value="mayorigual">&gt;=</option>
    																</select>
    															</div>
    														</div>
    														<div class="col-3 ps-0">
    															<label class="visually-hidden" for="deduc_valor2">Comparador 2</label>
    															<input data-target="#deduc_lbl_valor" data-compare="#deduc_comparador" data-valor="#deduc_valor" data-compare2="#deduc_comparador2" data-valor2="#deduc_valor2" onkeyup="deducciones.resumen( this );" type="number" id="deduc_valor2" name="deduc_valor2" class="form-control" aria-label="Monto">
    														</div>
                                                    		
                                                    		<div id="deduc_lbl_valor" class="col-12 text-muted fs-6 mt-1 mb-2">&nbsp;</div>
                                                    	</div>
                                                    	
                                                    	<div class="row">
                                                			<div id="frmcuarto" class="row mb-3" ></div>
    														<div class="d-grid gap-2">
    															<button data-target="#frmcuarto" onclick="deducciones.agregar_click( this );" class="btn btn-secondary" type="button">Agregar deducci&oacute;n</button>
    															<button id="btndeducGuardar" data-formcls="frmcompcls" data-firma="#deduc_lbl_valor" data-modificar="false" onclick="btnDeduccionGuardar( this );" class="btn btn-primary" type="button">Guardar deducciones</button>
    															<button id="btndeducModificar" data-formcls="frmcompcls" data-firma="#deduc_lbl_valor" data-modificar="true" onclick="btnDeduccionGuardar( this );" class="btn btn-primary btnsMods" type="button" style="display: none;">Modificar deducciones</button>
    															<button id="btndeducCancelar" data-modificar="false" onclick="btnDeducCancelar( this );" class="btn btn-danger" type="button" style="display: none;">Cancelar Cambio</button>
    														</div>
                                                    	</div>
                                                	</form>
                                                </div>
                                                <div class="tab-pane fade" id="pills-guardados" role="tabpanel" aria-labelledby="pills-guardados-tab">
                                                	<div class="row" id="contTb">
                                                    	<div class="col-3">
                                                        	<div class="d-flex align-items-center">
                                                              <strong>Loading...</strong>
                                                              <div class="spinner-border spinner-border-sm ms-auto" role="status" aria-hidden="true"></div>
                                                            </div>
                                                    	</div>
                                                    </div>
                                                </div>
                                            </div>
                    					</div>
                    				</div>
                    				
                    			</div>
                    		</div>
                        
                        </div>
                    </div>
                    
                	<div class="row">
                        <div class="col-12 mb-3" >
                        
                        	<div class="card">
                    			<div class="card-body">
                    				<h5 >Maestra de descuentos</h5>
                    				<p class="mb-4">Ingrese los registros de la tabla de porcentajes de descuentos y sus descripciones</p>
                    				
                    				<div class="row">
                    					<div id="tbMasterCont" class="col-12" ></div>
                					</div>
            					</div>
        					</div>
    					</div>
					</div>
                    
<?php               // TODO: Tare 153 - Crear la interface para crear reglas de descuentos ?>
                	<div class="row">
                        <div class="col-12 mb-3" >
                        
                        	<div class="card">
                    			<div class="card-body">
                    				<h5 >Reglas de descuentos</h5>
                    				<p class="mb-4">Cree reglas basado en los valores o respuestas que los usuarios dan en los formularios para hacer descuentos</p>
                    				
                    				<div class="row">

                                        <ul class="nav nav-tabs" id="reglas_myTab" role="tablist">
                                            <li class="nav-item" role="presentation">
                                        	    <button class="nav-link active" id="reglas_creartab" data-bs-toggle="tab" data-bs-target="#reglas_crear" type="button" role="tab" aria-controls="reglas_crear" aria-selected="true">Nueva regla</button>
                                            </li>
                                            <li class="nav-item" role="presentation">
                                            	<button class="nav-link" id="reglas_listatab" data-bs-toggle="tab" data-bs-target="#reglas_lista" type="button" role="tab" aria-controls="reglas_lista" aria-selected="false" onclick="listarReglas( this );" >Listado reglas</button>
                                            </li>
                                        </ul>
                                        <div class="tab-content" id="reglas_myTabContent">
                                            <div class="tab-pane fade show active pt-3" id="reglas_crear" role="tabpanel" aria-labelledby="reglas_creartab">

                                            	<div class="row mb-3">
                                            		<div class="col-12 mb-3">
                                            			<div class="form-floating">
                                                        	<textarea class="form-control" placeholder="Descripci&oacute;n de la regla" id="reglas_descr"></textarea>
                                                        	<label for="reglas_descr">Descripci&oacute;n de la regla</label>
                                                        </div>
                                            		</div>
                                            	</div>

        										<div class="row mb-3">
                                                    <div class="col-md-4">
        
                                                        <div class="dropdown">
                                                            <button class="btn btn-sm btn-primary dropdown-toggle py-0 mb-2" type="button" id="reglas_camposMenuListaFuente" data-bs-toggle="dropdown" aria-expanded="false">
                                                            	Seleccione los campos
                                                            </button>
                                                            <ul class="dropdown-menu" aria-labelledby="reglas_camposMenuListaFuente">
                                                                <?php foreach ( $d_json_campos as $kCamp ) : ?>
                                                                <li><button data-name="<?php echo $kCamp['titulo'] ?>" data-selval="#reglas_camposMenuListaFuente" data-target="#fields" data-value="<?php echo $kCamp['id'] ?>" class="dropdown-item" onclick="reglas.dibujarCampos( this );"><?php echo $kCamp['titulo'] ?></button></li>
                                                                <?php endforeach; ?>
                                                                <li><button data-name="Listas de referencia" data-selval="#reglas_camposMenuListaFuente" data-target="#fields" data-value="reflista" onclick="reglas.dibujarCampos( this );" class="dropdown-item" >Listas de referencia</button></li>
                                                            </ul>
                                                        </div>
                                                        
                                                        <div id="fields" class="border p-2 overflow-scroll" style="height: 100px;"></div>
                                                    </div>
                                            
                                            		<div class="col-md-4">
                                                        <h5>Operadores</h5>
                                                        <div id="operators" class="border p-2 d-flex flex-wrap">
                                                            <div class="draggable">=</div>
                                                            <div class="draggable">And</div>
                                                            <div class="draggable">Or</div>
                                                            <div class="draggable">Not</div>
                                                            <div class="draggable">(</div>
                                                            <div class="draggable">)</div>
                                                            <div class="draggable">&lt;</div>
                                                            <div class="draggable">&gt;</div>
                                                            <div class="draggable">&lt;=</div>
                                                            <div class="draggable">&gt;=</div>
                                                        </div>
                                            		</div>
                                            		
                                            		<div class="col-md-4">
                                                        <h5>Valores</h5>
                                                        <input type="text" id="valueInput" class="form-control mb-2" placeholder="Escribe un valor y presiona Enter">
                                                        <div id="values" class="border p-2 overflow-scroll" style="max-height: 70px;min-height: 40px;"></div>
                                                    </div>
                                            	</div>
                                            	
                                            	<div class="row mb-3">
													<div class="col mb-3">
                                                        <h5>&Aacute;rea de Construcci&oacute;n</h5>
                                                        <div id="expressionArea" class="dropzone d-flex"></div>
                                                    </div>
            									</div>

                                            	<div class="row mb-3">
            										<div class="col">
                                                        <button id="exportBtn" class="btn btn-primary">Exportar expresi&oacute;n</button>
                                                        <pre id="output" class="mt-3 bg-light p-3 border"></pre>
            										</div>
                                            	</div>
                                            	
                                            	<div class="row mb-3">
                                            		<h5>Maestra Deducciones</h5>
                                            		<div id="reglas_maestraDeduccionesCont" class="col overflow-auto" style="max-height: 180px;">
                                                		<div class="d-flex align-items-center ">
                                                            <strong>Cargando...</strong>
                                                            <div class="spinner-border ms-auto spinner-border-sm" role="status" aria-hidden="true"></div>
                                                        </div>
                                            		</div>
                                            	</div>
                                            	
                                            	<div class="row mb-3">
            									 	<div class="col-12 col-md-6 mb-3">
            											<button data-fn="limpiarGUI" data-vertab="#reglas_listatab" data-descr="#reglas_descr" data-idtarget="#reglas_id" data-expressionarea="#expressionArea" data-output="#output" data-maestradeduccionescont="#reglas_maestraDeduccionesCont" onclick="reglas.guardarGUI( this );" class="btn btn-primary w-100">Guardar Regla</button>
            										</div>
            										<div class="col-12 col-md-6 mb-3">
            											<button onclick="limpiarGUI( );" class="btn btn-danger w-100">Limpiar formulario</button>
            										</div>
            										<input type="hidden" id="reglas_id" value="" />
                                            	</div>
                                            
                                            </div>
                                            <div class="tab-pane fade pt-3" id="reglas_lista" role="tabpanel" aria-labelledby="reglas_listatab">
                                            
                                            	<div class="row table-responsive-custom" id="reglasContTb">
                                                	<div class="col-3">
                                                    	<div class="d-flex align-items-center">
                                                          <strong>Loading...</strong>
                                                          <div class="spinner-border spinner-border-sm ms-auto" role="status" aria-hidden="true"></div>
                                                        </div>
                                                	</div>
                                                </div>
                                            
                                            </div>
                                        </div>
                    					
                					</div>
            					</div>
        					</div>
    					</div>
					</div>
					
                    <?php endif; ?>

                </div>

            </div>

        </div>

    </div>
</div>

<script type="application/javascript" src="./temas/js/DataTables/datatables.min.js"></script>

<script type="application/javascript">
<?php // TODO: Tarea 153 - Se crea la clase ReglasClass que permita manejar los eventos desde el front ?>
const ReglasClass = function( ){
	const ls_json = <?php echo json_encode( $d_json ); ?>;
	
	let tableId = "tbInt" + ut.GetUUID();
	
	const self = this;
	
	self.obtenerCamposById = function( d ){
		let res = [];
		
		if ( Object.hasOwnProperty.call( ls_json, d ) ) {
    		res = ls_json[ d ];
		}
		
		return res;
	};
	
	self.obtenerTodosCampos = function(){
		return ls_json;
	};
	
	self.dibujarCampos = function( o ){
		const _o = jQuery( o );
		const dt = _o.data();
		
		const target = jQuery( dt["target"] );
		const selval = jQuery( dt["selval"] );
		const selnam = dt["name"] ;
		
		let mintxt = selnam;
		if( selnam.length > 35 ){
			mintxt = selnam.substr(0, 36) + '...';
		}
		
		selval.html( mintxt );
		
		const items = self.obtenerCamposById( dt['value'] );
		
		const defhtml = [];
		defhtml.push ( '<div class="draggable">' );
		defhtml.push ( items.join( '</div><div class="draggable">' ) );
		defhtml.push ( '</div>' );
		target.html( defhtml.join('') );
	};
	
	self.dibujarMaestra = function( d ){
		const data = d["data"];
		const target = jQuery( d['target'] );
		const html = [];
		
		html.push('<div class="list-group"> ');
		for (const ind in data ) {
        	if ( Object.hasOwnProperty.call( data, ind ) ) {
        		const _el = data[ ind ];
        		html.push('		<label class="list-group-item d-flex justify-content-start ">');
            	html.push('			<input data-id="' + _el['id'] + '" class="form-check-input me-1" type="checkbox" value="">');
            	html.push('			<div>');
            	html.push('				<h5 class="mb-0">' + _el['cod_interno'] + '</h5>' );
            	html.push('				<small class="text-muted">' + _el['cod_desc'] + ' - <strong>Porcentaje</strong> ' + _el['porcentaje'] + '</small>');
            	html.push('			</div>');
            	html.push('		</label>');
    		}
		}
		html.push('</div>');
		
		target.html( html.join('') );

	};
	
	self.guardarGUI = function( o ){
		const _o = jQuery( o );
		const dt = _o.data();
		
		const expressionarea = jQuery( dt[ 'expressionarea' ] );
		const output = jQuery( dt[ 'output' ] );
		const maestradeduccionescont = jQuery( dt['maestradeduccionescont'] );
		const descr = jQuery( dt['descr'] );
		
		const html = ( "" + expressionarea.html() );
		const exp = output.text();
		
		if( ("" + descr.val() ).length > 5 && expressionarea.find("div").length >= 3 && maestradeduccionescont.find(".form-check-input:checked").length > 0 ){
		
			let reglaid = ("" + jQuery( dt[ 'idtarget' ] ).val() );
    		if( reglaid.length == "" ){
    			reglaid = ut.GetUUID();
    			jQuery( dt[ 'idtarget' ] ).val( reglaid );
    		}
		
			const mdeduc = [];
    		maestradeduccionescont.find( ".form-check-input" ).each(function( i, o ){
                const _fci = jQuery( o );
                const dt = _fci.data();
                if( _fci.is(":checked") ){
                    mdeduc.push( dt['id'] );
                }
            });
    		
    		const opc = { 'id' : 'ajaxldr','size' : 'modal-sm' };
            const objmdl = mngModal.dibujar( opc );
            jQuery( objmdl ).modal('show');
    		
    		const sData = { "descr" : descr.val(), "reglaid": reglaid, "html" : html, "exp" : exp, "mdeduc": mdeduc};
    		self.guardar( { 
    			"data" : ut.b64EncodeUnicode( JSON.stringify( sData ) ), 
    			"fn" : function( rDt ){
    				jQuery( dt['vertab'] ).trigger( 'click' );
    				
    				if ( Object.hasOwnProperty.call( dt, "fn" ) ) {
    					eval( dt['fn'] + "()" );
    				}
    				
					setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
    			},
    			"fne" :  function( err ){
					const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
                    const alerta = jQuery(objmdlErr + ' div.alert');
                    alerta.attr('class','alert alert-danger');
                    
                    const jsondt = JSON.parse( err.responseText );
                    
                    alerta.html( jsondt['msj'] );
        
                    jQuery( objmdlErr ).modal('show');
    				setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
    			}
    		} );
		
		}
		else{
			alert( "Revise el \xE1rea de construcci\xF3n o la selecci\xF3n en la lista de la maestra de deducciones" );
		}
		
	};
	
	self.guardar = function( d ){
		const data = d[ 'data' ];
		const fn = d[ 'fn' ];
		const fne = d[ 'fne' ];
		
        const form_data = new FormData();
        form_data.append('vl', data);
        form_data.append('ajax', '<?php echo md5(IndexCtrl::API_ReglasVirtualAdd); ?>');
    
        __TransportarData(
            form_data,
            function( rDt ) {
            	fn( rDt );
            },
            function ( err ) {
                fne( err );
            }
        );
		
	};
	
	self.dibujarTb = function(){
		const html = [];
		
		html.push('<table id="' + tableId + '" class="table table-sm table-bordered table-striped table-hover responsive" style="width: 100%;"></table>');
		
		return html.join('');
	};
	
	self.dibujarDataTable = function( dt ){
		const tb = self.dibujarTb();
		jQuery( dt['contenedor'] ).html( tb );
		
		tbInter = jQuery( '#' + tableId ).DataTable({
            data: dt['data'],
            type: "text/json",
            columns: [
                { 
                	'title' : 'Id', 
                	data: 'id',
                	render : function(data, type, row){
                		const idIni = data.substr(0,3);
                		const idFin = data.substr(-5);
                		return idIni + "..." + idFin;
                	} 
            	},
                { 'title' : 'Descripci&oacute;n', data: 'descr', width: '200px' },
                { 'title' : 'Deducciones', data: 'regla' },
                { 'title' : 'Expresi&oacute;n', data: 'exp' },
                { 'title' : 'Creador', data: 'usuario' },
                { 'title' : 'Modificaci&oacute;n', data: 'fechamod' },
                { 
                	'title' : 'Acciones', 
                	data: null,
                	render : function(data, type, row){
                    	const html = [];
                        html.push('<button onclick="' + dt['editar'] + '(this);" data-id="' + data['id'] + '" class="btn m-0 px-1 py-0 text-muted text-primary-hover texttooltip" data-template="one' + data['id'] + '">');
                        html.push(' <i class="fe fe-edit fs-5"></i> ');
                        html.push(' <div id="one' + data['id'] + '" class="d-none"> ');
                        html.push('     <h6 class="mb-0 text-white">Editar</h6> ');
                        html.push(' </div> ');
                        html.push('</button> ');
                        
                        <?php if ( $usu->getPerfil_id() == IndexCtrl::PERFILES_SUPER_USUARIO || $usu->getPerfil_id() == IndexCtrl::PERFILES_ADMINISTRADOR || $usu->getPerfil_id() == IndexCtrl::PERFILES_FINANCIERO ) : ?>
                        html.push('<button onclick="reglas.eliminar_click(this);" data-id="' + data['id'] + '" class="btn m-0 px-1 py-0 text-muted text-primary-hover ms-3 texttooltip" data-template="two' + data['id'] + '"> ');
                        html.push(' <i class="fe fe-trash-2 fs-5"></i> ');
                        html.push(' <div id="two' + data['id'] + '" class="d-none"> ');
                        html.push('     <h6 class="mb-0 text-white">Eliminar</h6> ');
                        html.push(' </div> ');
                        html.push('</button> ');
                        <?php endif; ?>
                        
                		return html.join('');
                	}
            	}
            ],
            order: [[5, 'desc']],
            responsive: false,
            language: lengua_es,
            processing: true
        });
	};
	
	self.eliminar_click = function( o ){
		if( confirm('Desea eliminar este registro?') ){
			const opc = { 'id' : 'ajaxldr','size' : 'modal-lg' };
            const objmdl = mngModal.dibujar( opc );
            jQuery( objmdl ).modal('show');
            
    		const _o = jQuery( o );
    		const dt = _o.data();
    		
    		const data = { "reglaid" : dt['id'] };
    		
    		const form_data = new FormData();
            form_data.append('vl', ut.b64EncodeUnicode( JSON.stringify( data ) ) );
            form_data.append('ajax', '<?php echo md5( IndexCtrl::API_ReglasVirtualDel ); ?>');
                
    		__TransportarData(
                form_data,
                function( oR ) {
                    const fila = _o.closest('tr');
                    tbInter.row(fila).remove().draw();
    
                    setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
                },
                function ( err ) {
                	const oErr = err.responseJSON;
                    const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
                    const alerta = jQuery(objmdlErr + ' div.alert');
                    alerta.attr('class','alert alert-danger');
                    alerta.html( oErr['msj'] );
        
                    jQuery( objmdlErr ).modal('show');
                    setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
                }
            );
		}
	};
	
	self.editar_click = function( o, fn ){
		const opc = { 'id' : 'ajaxldr','size' : 'modal-lg' };
        const objmdl = mngModal.dibujar( opc );
        jQuery( objmdl ).modal('show');
        
		const _o = jQuery( o );
		const dt = _o.data();
		
		const oData = { "reglaid" : dt['id'] };
		
		const form_data = new FormData();
        form_data.append('ajax', '<?php echo md5( IndexCtrl::API_ReglasVirtualHelperGet ); ?>');
        form_data.append('vl', ut.b64EncodeUnicode( JSON.stringify( oData ) ) );
        
        __TransportarData(
            form_data,
            function( oR ) {
            	fn( oR );
            	setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
            },
            function ( err ) {
            	const oErr = err.responseJSON;
                const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
                const alerta = jQuery(objmdlErr + ' div.alert');
                alerta.attr('class','alert alert-danger');
                alerta.html( oErr['msj'] );
        
                jQuery( objmdlErr ).modal('show');
                setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
            }
        );
	};
	
};
const reglas = new ReglasClass();

const limpiarGUI = function(){
	jQuery("#expressionArea").html( '' );
	jQuery("#output").html( '' );
	jQuery("#reglas_id").val( '' );
	jQuery( "#reglas_descr" ).val('');
	
	jQuery("#reglas_maestraDeduccionesCont .form-check-input").prop('checked', false);
};

const btnReglasEditar = function( o ){
	reglas.editar_click( o , function( dt ){
		jQuery("#reglas_creartab").trigger('click');
		
		jQuery("#expressionArea").html( dt['html'] );
		jQuery("#output").html( dt['exp'] );
		jQuery("#reglas_id").val( dt['reglaid'] );
		jQuery("#reglas_descr").val( dt['descr'] );
		
		jQuery("#reglas_maestraDeduccionesCont .form-check-input").prop('checked', false);
		
		const mdeduc = dt[ 'mdeduc' ];
		for (const ind in mdeduc ) {
        	if ( Object.hasOwnProperty.call( mdeduc, ind ) ) {
        		const _el = mdeduc[ ind ];
        		jQuery("[data-id=" + _el + "]").prop('checked', true);
    		}
		}
	});
};

const listarReglas = function( o ){
    const opc = { 'id' : 'ajaxldr','size' : 'modal-sm' };
    const objmdl = mngModal.dibujar( opc );
    jQuery( objmdl ).modal('show');
    
    const form_data = new FormData();
    form_data.append('ajax', '<?php echo md5( IndexCtrl::API_ReglasVirtualGetAjax ); ?>');
    
    __TransportarData(
        form_data,
        function( rDt ) {
        	reglas.dibujarDataTable( { 'contenedor' : '#reglasContTb', 'data' : rDt , 'editar' : 'btnReglasEditar' } );
        	setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
        },
        function ( err ) {
        	const oErr = err.responseJSON;
            const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
            const alerta = jQuery(objmdlErr + ' div.alert');
            alerta.attr('class','alert alert-danger');
            alerta.html( oErr['msj'] );
    
            jQuery( objmdlErr ).modal('show');
            setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
        }
    );
};

</script>

<script type="application/javascript">
jQuery( document ).ready(function(){
	var drake = dragula([
        document.getElementById('fields'),
        document.getElementById('operators'),
        document.getElementById('values'),
        document.getElementById('expressionArea')
    ], {
        copy: function (el, source) {
        	return source.id !== 'expressionArea';
        },
        accepts: function (el, target) {
        	return target.id === 'expressionArea';
        },
        removeOnSpill: true
    });

    document.getElementById('valueInput').addEventListener('keydown', function(e) {
        if (e.key === 'Enter') {
            let val = e.target.value.trim();
            if ( val ) {
                let div = document.createElement('div');
                div.className = 'draggable';
                div.textContent = `"${val}"`;
                document.getElementById('values').appendChild(div);
                e.target.value = '';
            }
        }
    });

    document.getElementById('exportBtn').addEventListener('click', function() {
        let items = document.querySelectorAll('#expressionArea .draggable');
        let expression = Array.from(items).map(el => el.textContent).join(' ');
        document.getElementById('output').textContent = expression;
    });
});
</script>

<script type="application/javascript">
<?php // TODO: Tarea 147 - Crea una clase en front que permite controlar las tareas de la la Maestra de descuentos ?>
const GestionDataTable = function(instancia, containerId, columnasIniciales) {
    const self = this;
    let table = null;
    let tableId = "tbJson_" + ut.GetUUID();
    
    let rowGlb;
    let currentData = [];
    
    self.datos = [];

    self.init = function() {
    	/*
        let html = `
            <div class="dt-buttons-container" style="margin-bottom:15px;">
                <button type="button" class="btn btn-primary btn-sm btn-nuevo-${tableId}">Nuevo Registro</button>
                <button type="button" class="btn btn-primary btn-sm btn-guardar-${tableId}">Guardar</button>
                <input type="file" class="file-import-${tableId}" style="display:none" accept=".json">
                <button type="button" onclick="jQuery('.file-import-${tableId}').click()">Importar JSON</button>
            </div>
            <div class="table-responsive-custom">
            	<table id="${tableId}" class="table table-sm table-bordered table-striped table-hover responsive display" style="width:100%"></table>
            </div>
        `;
        */
        let html = `
            <div class="dt-buttons-container" style="margin-bottom:15px;">
                <button type="button" class="btn btn-primary btn-sm btn-nuevo-${tableId}">Nuevo Registro</button>
                <button type="button" class="btn btn-primary btn-sm btn-guardar-${tableId}">Guardar</button>
                <button type="button" class="btn btn-primary btn-sm btn-lista-${tableId}">Items grupo</button>
            </div>
            <div class="row table-responsive-custom">
            	<table id="${tableId}" class="table table-sm table-bordered table-striped table-hover responsive display" style="width:100%"></table>
            </div>
        `;
        
        jQuery(containerId).html(html);

        table = jQuery(`#${tableId}`).DataTable({
            data: self.datos,
            columns: [
                ...columnasIniciales,
                {
                    title: "Acciones",
                    data: null,
                    width: 30,
                    render: function(data, type, row) {
                        return `
                            <button class="btn m-0 px-1 py-0 text-muted text-primary-hover texttooltip btn-edit-row" data-template="btnEditTpl-${tableId}">
                            	<i class="fe fe-edit fs-5"></i>
                            	<div id="btnEditTpl-${tableId}" class="d-none">
                            		<h6 class="mb-0 text-white">Editar</h6>
                            	</div>
                            </button>
                            <button class="btn m-0 px-1 py-0 text-muted text-primary-hover ms-0 texttooltip btn-delete-row" data-template="btnDelTpl-${tableId}">
                            	<i class="fe fe-trash-2 fs-5"></i>
                            	<div id="btnDelTpl-${tableId}" class="d-none">
                            		<h6 class="mb-0 text-white">Eliminar</h6>
                            	</div>
                            </button>
                        `;
                    }
                }
            ],
            order: [[5, 'desc']],
            responsive: false,
            language: lengua_es,
        });

        self.bindEvents();
    };
    
    self.getData = function( d ){
    	const fn = d['fn'];
        const form_data = new FormData();
        form_data.append('ajax', '<?php echo md5(IndexCtrl::API_MaestrasVirtualGet); ?>');
    
        __TransportarData(
            form_data,
            function( oDt ) {
            	try {
                    const json = JSON.parse( ut.b64DecodeUnicode( oDt ) );
                    table.clear().rows.add(json).draw();
                    self.actualizarEstado();
                } catch (err) {
                    console.error("Error al cargar JSON", err);
                }
            	fn( oDt );
            },
            function ( err ) {
                const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
                const alerta = jQuery(objmdlErr + ' div.alert');
                alerta.attr('class','alert alert-danger');
                alerta.html( err.responseText );
    
                jQuery( objmdlErr ).modal('show');
            }
        );
    };
    
    self.setFieldData = function(){
    	ut.validarFrm( 'formmaestraCls' + tableId , function (r) {
    		currentData.grupo = r['maestra-grupo-' + tableId ];
    		currentData.cod_interno = r['maestra-cod_interno-' + tableId ];
    		currentData.cod_desc = r['maestra-cod_desc-' + tableId ];
    		currentData.porcentaje = r['maestra-porcentaje-' + tableId ];
    		
            rowGlb.data(currentData).draw();
            self.actualizarEstado();
    	});
    };
    
    self.grpItems_Eliminar = function( o ){
    	const _o = jQuery( o );
    	const dt = _o.data();
    	
    	const li = jQuery( dt['li'] );
    	const ul = jQuery( dt['ul'] );
    	
    	if( confirm( "Desea eliminar este registro?" ) ){
    		li.hide("fast", function(){
    			li.remove();
    			
    			const estanuevo = ul.find('li');
    			if( estanuevo.length == 0 ){
            		ul.html( '<li class="list-group-item estanuevo">No hay items</li>' );
            	}
    		});
    	}
    };
    
    self.grpItems_GuardarLista = function( o ){
    	const _o = jQuery( o );
    	const dt = _o.data();
    	
    	_o.attr( "disabled", "disabled" );
    	_o.html( validadorGlob.ajaxspinner() );
    	
    	const lis = jQuery( dt['ul'] );
    	
    	const data = [];
    	
    	lis.find( 'li' ).each(function(i,obj){
    		const _obj = jQuery( obj );
    		const dtObj = _obj.data();
    		data.push( dtObj['value'] );
    	});
    	
    	const blob = JSON.stringify( data );
        const dt64 = ut.b64EncodeUnicode( blob );
		
		const form_data = new FormData();
        form_data.append('ajax', '<?php echo md5(IndexCtrl::API_MaestrasGrpVirtualAdd ); ?>' );
        form_data.append('vl', dt64 );
    
        __TransportarData(
            form_data,
            function( oDt ) {
            	_o.removeAttr( "disabled" );
    			_o.html( "Guardar" );
            },
            function ( err ) {
                const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
                const alerta = jQuery(objmdlErr + ' div.alert');
                alerta.attr('class','alert alert-danger');
                alerta.html( err.responseText );
    
                jQuery( objmdlErr ).modal('show');
            }
        );
        
    };
    
    const grpItemsTpl = function( txt, target ){
		const firma = ut.b64EncodeUnicode( ( "" + txt ).toLowerCase() ).replace(/==/ig, "").replace(/=/ig, "");
		
		const liId = 'li-' + firma;
		
		const htmlli = [];
		
    	htmlli.push( '<li id="' + liId + '" data-value="' + txt + '" class="list-group-item d-flex justify-content-between align-items-center" >' );
    	htmlli.push( '	<div class="d-flex align-items-center" >' );
    	htmlli.push( '		' + txt + '' );
    	htmlli.push( '	</div>' );
    	htmlli.push( '	<div >' );
    	htmlli.push( '		<button data-ul="#' + target.attr('id') + '" data-li="#' + liId + '" class="btn-close" aria-label="Close" onclick="' + instancia + '.grpItems_Eliminar( this );"></button>' );
    	htmlli.push( '	</div>' );
    	htmlli.push( '</li>' );
    	
    	return { "id" : liId, "html" : htmlli.join('') }
    };
    
    self.grpItems_Agregar = function( o ){
    	const _o = jQuery( o );
    	const dt = _o.data();
    	
    	const target = jQuery( dt['target'] );
    	const valor = jQuery( dt['valor'] );
    	
    	ut.validarFrm( 'formmaestraItemGrpCls' + tableId, function (r) {
    	
			const txt = jQuery.trim( valor.val() );
    	
        	if( txt != null && ("" + txt ).length > 0 ){
    			const estanuevo = target.find('.estanuevo');
    			
    			const obLi = grpItemsTpl( txt, target );
    			const liId = obLi['id'];
    			const unicoItem = target.find( '#' + liId );
    			
    			if( unicoItem.length ) {
    				alert('El registro ya existe');
    			}
    			else{
    				const htmlli = [];
                	htmlli.push( '<li id="' + liId + '" data-value="' + txt + '" class="list-group-item d-flex justify-content-between align-items-center" >' );
                	htmlli.push( '	<div class="d-flex align-items-center" >' );
                	htmlli.push( '		' + txt + '' );
                	htmlli.push( '	</div>' );
                	htmlli.push( '	<div >' );
                	htmlli.push( '		<button data-ul="#' + target.attr('id') + '" data-li="#' + liId + '" class="btn-close" aria-label="Close" onclick="' + instancia + '.grpItems_Eliminar( this );"></button>' );
                	htmlli.push( '	</div>' );
                	htmlli.push( '</li>' );
                	
                	if( estanuevo.length ){
                		target.html( obLi['html'] );
                	}
                	else{
                		target.append( obLi['html'] );
                	}
                	
                	agregarAgarre( { "contenedor" : target.attr('id'), "hijos": 'list-group-item' } );
                	
    			}
        	
        	}
    	
    	});
    };
    
    const maestraGrpObtener = function( fn ){
    
		const form_data = new FormData();
        form_data.append('ajax', '<?php echo md5(IndexCtrl::API_MaestrasGrpVirtualGet ); ?>');
    
        __TransportarData(
            form_data,
            function( oR ) {
            	fn( oR );
            },
            function ( err ) {
                const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
                const alerta = jQuery(objmdlErr + ' div.alert');
                alerta.attr('class','alert alert-danger');
                alerta.html( err.responseText );
    
                jQuery( objmdlErr ).modal('show');
            }
        );
    
    };
    
    self.bindEvents = function() {
        jQuery(`#${tableId} tbody`).on('click', '.btn-delete-row', function() {
        
        	if(	confirm('Desea eliminar este registro?') ){
        		table.row(jQuery(this).parents('tr')).remove().draw();
            	self.actualizarEstado();
        	}
        
        });

        jQuery(`#${tableId} tbody`).on('click', '.btn-edit-row', function() {
<?php       //TODO: Tarea 148 - Agregar la capacidad para modificar datos desde lo que existe?>
        	const selContId = "maestragrpContSel-" + tableId;
        	const selId = "maestra-grupo-" + tableId;
        	
            rowGlb = table.row(jQuery(this).parents('tr'));
            currentData = rowGlb.data();
            
            const modalId = 'stcMdl-' + tableId;
            if( jQuery( "#" + modalId ).length ){
            	jQuery( "#" + modalId ).remove();
            }
            
            const modalHtml = [];
            modalHtml.push('<div class="modal fade" id="stcMdl-' + tableId + '" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="stcBLabel' + tableId + '" aria-hidden="true">');
			modalHtml.push('	<div class="modal-dialog">');
			modalHtml.push('		<div class="modal-content">');
			modalHtml.push('			<div class="modal-header">');
			modalHtml.push('				<h5 class="modal-title" id="stcBLabel' + tableId + '">Registro</h5>');
			modalHtml.push('				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>');
			modalHtml.push('			</div>');
			modalHtml.push('			<div class="modal-body">');
			
			modalHtml.push('				<form id="formmaestra' + tableId + '" class="formmaestraCls' + tableId + '">');
			modalHtml.push('					<div id="' + selContId + '" class="form-floating mb-3">');
			modalHtml.push('						' + validadorGlob.ajaxspinner() );
			modalHtml.push('					</div>');
			
			let cod_interno = "";
			if( ("" + currentData['cod_interno']).length > 0 ){
				cod_interno = currentData['cod_interno'];
			}
			modalHtml.push('					<div class="form-floating mb-3">');
			modalHtml.push('						<input value="' + cod_interno + '" required="required" type="text" class="form-control" id="maestra-cod_interno-' + tableId + '" name="maestra-cod_interno-' + tableId + '" placeholder="0000">');
			modalHtml.push('						<label for="maestra-cod_interno-' + tableId + '">C&oacute;digo interno</label>');
			modalHtml.push('					</div>');
			
			let cod_desc = "";
			if( ("" + currentData['cod_desc']).length > 0 ){
				cod_desc = currentData['cod_desc'];
			}
			modalHtml.push('					<div class="form-floating mb-3">');
			modalHtml.push('						<input value="' + cod_desc + '" required="required" type="text" class="form-control" id="maestra-cod_desc-' + tableId + '" name="maestra-cod_desc-' + tableId + '" placeholder="Descripci&oacute;n">');
			modalHtml.push('						<label for="maestra-cod_desc-' + tableId + '">Descripci&oacute;n c&oacute;digo</label>');
			modalHtml.push('					</div>');
			
			let porcentaje = "";
			if( ("" + currentData['porcentaje']).length > 0 ){
				porcentaje = currentData['porcentaje'];
			}
			modalHtml.push('					<div class="form-floating mb-3">');
			modalHtml.push('						<input value="' + porcentaje + '" required="required" type="number" class="form-control" id="maestra-porcentaje-' + tableId + '" name="maestra-porcentaje-' + tableId + '" placeholder="0.0" step="any">');
			modalHtml.push('						<label for="maestra-porcentaje-' + tableId + '">Porcentaje</label>');
			modalHtml.push('					</div>');
			modalHtml.push('				</form>');
			
			modalHtml.push('			</div>');
			modalHtml.push('			<div class="modal-footer">');
			modalHtml.push('				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>');
			modalHtml.push('				<button onclick="' + instancia + '.setFieldData();" type="button" class="btn btn-primary" data-bs-dismiss="modal">Actualizar tabla</button>');
			modalHtml.push('			</div>');
			modalHtml.push('		</div>');
			modalHtml.push('	</div>');
			modalHtml.push('</div>');
            
            const mdl = jQuery( modalHtml.join('') );
            mdl.modal('show');
            
            maestraGrpObtener(function( oR ){
            
				const oDt = JSON.parse( ut.b64DecodeUnicode( oR ) );
				
				const htmltmp = [];
				htmltmp.push('<div class="form-floating">');
				htmltmp.push('	<select class="form-select" id="' + selId + '" name="' + selId + '" aria-label="Grupos">');
            	if( oDt.length > 0 ){
            		for (const ind in oDt ) {
                    	if ( Object.hasOwnProperty.call( oDt, ind ) ) {
                    		const _el = oDt[ ind ];
                    		let selItem = "";
                			if( currentData['grupo'] == _el ){
                				selItem = 'selected="selected"';
                			}
                    		
                    		htmltmp.push('		<option value="' + _el + '" ' + selItem + '>' + _el + '</option>');
                		}
            		}
            		
            	}
            	htmltmp.push('		</select>');
            	htmltmp.push('	<label for="' + selId + '">Grupo</label>');
            	htmltmp.push('</div>');
            	jQuery("#" + selContId).html( htmltmp.join('') );
            
            });
            
        });
        jQuery(`.btn-nuevo-${tableId}`).on('click', function() {
        	const fData = ictrl.getFormattedDate();
        	
            const nuevoObj = { id: ut.GetUUID(), grupo: "grp", cod_interno: "0000", cod_desc: "Descripci&oacute;n", porcentaje: "0.0", fecha: fData, creador: "<?php echo $usu->getNombres() . " " . $usu->getApellidos() ?>" };
            table.row.add(nuevoObj).draw();
            self.actualizarEstado();
        });

        jQuery(`.btn-guardar-${tableId}`).on('click', function() {
			const opc = { 'id' : 'ajaxldr','size' : 'modal-sm' };
            const objmdl = mngModal.dibujar( opc );
            jQuery( objmdl ).modal('show');
            
            const data = table.rows().data().toArray();
            const blob = JSON.stringify( data );
            const dt64 = ut.b64EncodeUnicode( blob );
            
            const form_data = new FormData();
            form_data.append('ajax', '<?php echo md5(IndexCtrl::API_MaestrasVirtualAdd ); ?>');
            form_data.append('vl', dt64);
        
            __TransportarData(
                form_data,
                function( o ) {
                    setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
                },
                function ( err ) {
                    const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
                    const alerta = jQuery(objmdlErr + ' div.alert');
                    alerta.attr('class','alert alert-danger');
                    alerta.html( err.responseText );
        
                    jQuery( objmdlErr ).modal('show');
                    setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
                }
            );
        });

    	jQuery(`.btn-lista-${tableId}`).on('click', function() {
    		const frmId = 'formmaestraItemGrp' + tableId;
    		const ulId = 'maestra-listGrp-' + tableId ;
    		const idItemVacio = 'maestra-itemEmpty-' + tableId ;
    		
    		const modalId = 'stcMdlItemsGrp-' + tableId;
    		if( jQuery( "#" + modalId ).length ){
    			jQuery( "#" + modalId ).remove();
    		}
    		
            const modalHtml = [];
            modalHtml.push('<div class="modal fade" id="stcMdlItemsGrp-' + tableId + '" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="stcItemsBLabel' + tableId + '" aria-hidden="true">');
			modalHtml.push('	<div class="modal-dialog modal-lg modal-dialog-scrollable">');
			modalHtml.push('		<div class="modal-content">');
			modalHtml.push('			<div class="modal-header">');
			modalHtml.push('				<h5 class="modal-title" id="stcItemsBLabel' + tableId + '">Items del grupo</h5>');
			modalHtml.push('				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>');
			modalHtml.push('			</div>');
			modalHtml.push('			<div class="modal-body">');
			
			modalHtml.push('				<form id="' + frmId + '" class="formmaestraItemGrpCls' + tableId + ' d-flex bd-highlight">');
			modalHtml.push('					<div class="form-floating mb-3 flex-grow-1 bd-highlight">');
			modalHtml.push('						<input required="required" type="text" class="form-control" id="maestra-itemgrupo-' + tableId + '" name="maestra-itemgrupo-' + tableId + '" placeholder="item nuevo">');
			modalHtml.push('						<label for="maestra-itemgrupo-' + tableId + '">Grupo</label>');
			modalHtml.push('					</div>');
			
			modalHtml.push('					<div class="bd-highlight ms-3">');
			modalHtml.push('						<button data-valor="#maestra-itemgrupo-' + tableId + '" data-target="#maestra-listGrp-' + tableId + '" onclick="' + instancia + '.grpItems_Agregar( this );" type="button" class="btn btn-primary" >');
			modalHtml.push('							Agregar item');
			modalHtml.push('						</button>');
			modalHtml.push('					</div>');
			
			modalHtml.push('				</form>');
			
			modalHtml.push('				<div class="card shadow-lg" style="">');
			modalHtml.push('					<div class="card-header">');
			modalHtml.push('						<h5>Items existentes</h5>');
			modalHtml.push('					</div>');
			modalHtml.push('					<div class="card-body">');
			modalHtml.push('						<ul id="' + ulId + '" class="list-group">');
			modalHtml.push('							<li id="' + idItemVacio + '" class="list-group-item estanuevo">' + validadorGlob.ajaxspinner() + '</li>');
			modalHtml.push('						<ul >');
			modalHtml.push('					</div>');
			modalHtml.push('				</div >');
			
			modalHtml.push('			</div>');
			modalHtml.push('			<div class="modal-footer">');
			modalHtml.push('				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>');
			modalHtml.push('				<button data-ul="#' + ulId + '" onclick="' + instancia + '.grpItems_GuardarLista( this );" type="button" class="btn btn-primary">Guardar</button>');
			modalHtml.push('			</div>');
			modalHtml.push('		</div>');
			modalHtml.push('	</div>');
			modalHtml.push('</div>');
            
            const mdl = jQuery( modalHtml.join('') );
            mdl.modal('show');
            
            maestraGrpObtener(function( oR ){
            
				const oDt = JSON.parse( ut.b64DecodeUnicode( oR ) );
                	
            	if( oDt.length > 0 ){
            		const htmltmp = [];
            		for (const ind in oDt ) {
                    	if ( Object.hasOwnProperty.call( oDt, ind ) ) {
                    		const _el = oDt[ ind ];
                    		const oItem = grpItemsTpl( _el, jQuery( ulId ) );
                    		htmltmp.push( oItem['html'] );
                		}
            		}
            		jQuery("#" + ulId).html( htmltmp.join('') );
            		agregarAgarre( { "contenedor" : ulId, "hijos": 'list-group-item' } );
            	}
            	else{
            		jQuery( "#" + ulId ).html('No hay items');
            	}
            
            });
            
            mdl.find( '#' + frmId ).on('submit', function(e) {
                e.preventDefault();
                
                const idBtnTmp = 'btnAddItemTrigger-' + tableId;
                if( jQuery( "#" + idBtnTmp ).length ){
                	jQuery( "#" + idBtnTmp ).remove();
                }
                
                const btnTmp = '<button id="' + idBtnTmp + '" data-valor="#maestra-itemgrupo-' + tableId + '" data-target="#maestra-listGrp-' + tableId + '" ><button>'; 
                self.grpItems_Agregar( jQuery( btnTmp ) );
                return false;
            });
            
    	});
    	
        jQuery(`.file-import-${tableId}`).on('change', function(e) {
            const file = e.target.files[0];
            if (!file) return;

            const reader = new FileReader();
            reader.onload = function(evt) {
                try {
                    const json = JSON.parse(evt.target.result);
                    table.clear().rows.add(json).draw();
                    self.actualizarEstado();
                } catch (err) {
                    console.error("Error al cargar JSON", err);
                }
            };
            reader.readAsText(file);
        });
        
    };

    self.actualizarEstado = function() {
        self.datos = table.rows().data().toArray();
    };
    
    self.obtenerDatos = function() {
        return table.rows().data().toArray();
    };
};
</script>

<script type="application/javascript">
<?php 
/*
 * @yalfonso
 * TODO: Tarea 20 - Crear m&eacute;todo que guarda la configuraci&oacute;n global de los perfiles de contabilidad
 */
?>
const btnDeduccionGuardar = function( o ){
	deducciones.guardar_click( o , function(){
		jQuery('#pills-guardados-tab').trigger('click');
		jQuery('#frmcuarto').html('');
		document.getElementById('frmcomp').reset();
		jQuery('#deduc_comparador,#deduc_valor,#deduc_comparador2,#deduc_valor2').prop('disabled', false);
	});
};
<?php 
/*
 * @yalfonso
 * TODO: Tarea 21 - Crear m&eacute;todo que modifica la configuraci&oacute;n global de los perfiles de contabilidad
 */
?>
const btnDeduccionEditar = function( o ){
	jQuery( o ).attr('data-target', '#frmcuarto');
	deducciones.editar_click( o , function( dt ){
		jQuery('#pills-crear-tab').tab('show');
		jQuery('#frmcuarto').html('');
		document.getElementById('frmcomp').reset();
		jQuery('#deduc_comparador,#deduc_valor,#deduc_comparador2,#deduc_valor2').prop('disabled', true);
		jQuery('#btndeducModificar, #btndeducCancelar').show('fast');
		jQuery('#btndeducGuardar').hide('fast');
	});
};

const btnDeducCancelar = function( o ){
	jQuery('#frmcuarto, #deduc_lbl_valor').html('');
	document.getElementById('frmcomp').reset();
	jQuery('#deduc_comparador,#deduc_valor,#deduc_comparador2,#deduc_valor2').prop('disabled', false);
	jQuery('#btndeducModificar, #btndeducCancelar').fadeOut('fast');
	jQuery('#btndeducGuardar').show('fast');
};
<?php 
/*
 * @yalfonso
 * TODO: Tarea 22 - Crear m&eacute;todo lista las posibles deducciones que aplican para el usuario que radica cuenta de cobro
 */
?>
const listarDeducciones = function(){
    const opc = { 'id' : 'ajaxldr','size' : 'modal-sm' };
    const objmdl = mngModal.dibujar( opc );
    jQuery( objmdl ).modal('show');
    
    const form_data = new FormData();
    form_data.append('ajax', '<?php echo md5( IndexCtrl::API_DeduccionesVirtualGetAjax ); ?>');
    
    __TransportarData(
        form_data,
        function( o ) {
        	deducciones.dibujarDataTable( { 'contenedor' : '#contTb', 'data' : o , 'editar' : 'btnDeduccionEditar' } );
        	setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
        },
        function ( err ) {
        	const oErr = err.responseJSON;
            const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
            const alerta = jQuery(objmdlErr + ' div.alert');
            alerta.attr('class','alert alert-danger');
            alerta.html( oErr['msj'] );
    
            jQuery( objmdlErr ).modal('show');
            setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
        }
    );
};


/**
 * Configura y controla el comportamiento del botón "Firmar" en el formulario.
 *
 * @param {Object} o Parámetros y estado necesarios para la configuración del botón.
 * @return void
 */
const btnFirmCfgFrm = function( o ){
    const opc = { 'id' : 'ajaxldr','size' : 'modal-sm' };
    const objmdl = mngModal.dibujar( opc );
    jQuery( objmdl ).modal('show');

    var _o = jQuery( o );
    var id = _o.attr('id');
    var vl = null;
    if( (""+_o.attr('type')).toLowerCase() == "checkbox" ){
    	vl = _o.is(':checked');
    }
    else{
    	vl = _o.val();
    }

    const form_data = new FormData();
    form_data.append('id', id);
    form_data.append('vl', vl);
    form_data.append('ufull', '<?php echo $usu->getNombres() . " " . $usu->getApellidos(); ?>');
    form_data.append('ajax', '<?php echo md5(IndexCtrl::API_AgregarConfigCorp); ?>');

    __TransportarData(
        form_data,
        function( o ) {
            setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
        },
        function ( err ) {
            const objmdlErr = mngModal.dibujar( { 'id' : 'mdlError', 'title' : 'Error','btnCerrarX' : true, 'level' : 'err', 'size' : 'modal-sm' } );
            const alerta = jQuery(objmdlErr + ' div.alert');
            alerta.attr('class','alert alert-danger');
            alerta.html( err.responseText );

            jQuery( objmdlErr ).modal('show');
            setTimeout(function(){ jQuery( objmdl ).modal('hide'); }, <?php echo IndexCtrl::TIEMPO_AJAX_LDN ?>);
        }
    );
    
};

let miGestion;
let deducciones;

jQuery( document ).ready(function(){
	deducciones = new Deducciones();
	
    const misColumnas = [
        { title: "ID", data: "id", width: 300 },
        { title: "Grupo", data: "grupo" },
        { title: "C&oacute;digo interno", data: "cod_interno" },
        { title: "Descripci&oacute;n c&oacute;digo", data: "cod_desc" },
        { title: "%", data: "porcentaje" },
        { title: "Fecha", data: "fecha", width: 150 },
        { title: "Creador", data: "creador", width: 150 }
    ];
    
    miGestion = new GestionDataTable("miGestion", "#tbMasterCont", misColumnas);
    miGestion.init();
    miGestion.getData( { 
    	fn : function( oDt ){
    		const dataDeducciones = JSON.parse( ut.b64DecodeUnicode( oDt ) );
    		
    		reglas.dibujarMaestra( { "target" : "#reglas_maestraDeduccionesCont", "data" : dataDeducciones } );
    	} 
    });
	
});
</script>