<?php
use src\sistema\Menubar\Menubar;
use src\sistema\Headerbar\Headerbar;

OperacionesCtrl::authRequOff();
?>
<div id="db-wrapper" class="" style="background-color: #fefcfb; display: none;" >
    <!-- navbar vertical -->
    <!-- Sidebar -->
    <?php $crum = Menubar::DibujarMenuHome(); ?>

    <!-- Page Content -->
    <div id="page-content">

        <!-- Page Header -->
        <?php Headerbar::DibujarHeaderHome( ); ?>
            
        <!-- Container fluid -->
        <div class="container-fluid p-4">
        
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12">
                    <div class="border-bottom pb-4 mb-4 d-lg-flex justify-content-between align-items-center">
                        <div class="mb-3 mb-lg-0">
                            <h1 class="mb-0 h2 fw-bold"><?php echo $crum['l2']; ?></h1>

                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="#" style="color: #cc5b08; "><?php echo $crum['l1']; ?></a></li>
                                    <li class="breadcrumb-item active" aria-current="page">
                                        <?php echo $crum['l2']; ?>
                                    </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </div>
            </div>
        
            <div class="row">
            	<div class="col-lg-12 col-md-12 col-12">
            		Ok! Pref
            	</div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
jQuery( document ).ready(function(){
	home.navLogin(function(){
		jQuery('#db-wrapper').fadeIn('fast');
	});
});
</script>